

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * AmendAttributes
 */

// CHECKSTYLE:OFF
public class AmendAttributes 
// CHECKSTYLE:ON
{
  /**
   * Gets or Sets amendmentType
   */
  public enum AmendmentTypeEnum {
    /**
    * The ADMINISTRATIVE option of this AmendAttributes
    */
    ADMINISTRATIVE("Administrative"),
    
    /**
    * The RENEWAL option of this AmendAttributes
    */
    RENEWAL("Renewal"),
    
    /**
    * The AMENDMENT option of this AmendAttributes
    */
    AMENDMENT("Amendment"),
    
    /**
    * The TERMINATION option of this AmendAttributes
    */
    TERMINATION("Termination"),
    
    /**
    * The PRICEUPDATE option of this AmendAttributes
    */
    PRICEUPDATE("PriceUpdate");

    private String value;

    AmendmentTypeEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type AmendAttributes
    */
    @JsonCreator
    @Nonnull public static AmendmentTypeEnum fromValue(@Nonnull final String value) {
      for (AmendmentTypeEnum b : AmendmentTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("amendmentType")
  private AmendmentTypeEnum amendmentType;

  @JsonProperty("amendmentReason")
  private String amendmentReason;

  @JsonProperty("isTemplateUpgradeRequired")
  private Boolean isTemplateUpgradeRequired;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the amendmentType of this {@link AmendAttributes} instance and return the same instance.
   *
   * @param amendmentType  The amendmentType of this {@link AmendAttributes}
   * @return The same instance of this {@link AmendAttributes} class
   */
   @Nonnull public AmendAttributes amendmentType(@Nonnull final AmendmentTypeEnum amendmentType) {
    this.amendmentType = amendmentType;
    return this;
  }

   /**
   * Get amendmentType
   * @return amendmentType  The amendmentType of this {@link AmendAttributes} instance.
  **/
  @Nonnull public AmendmentTypeEnum getAmendmentType() {
    return amendmentType;
  }

  /**
  * Set the amendmentType of this {@link AmendAttributes} instance.
  *
  * @param amendmentType  The amendmentType of this {@link AmendAttributes}
  */
  public void setAmendmentType( @Nonnull final AmendmentTypeEnum amendmentType) {
    this.amendmentType = amendmentType;
  }

   /**
   * Set the amendmentReason of this {@link AmendAttributes} instance and return the same instance.
   *
   * @param amendmentReason  The amendmentReason of this {@link AmendAttributes}
   * @return The same instance of this {@link AmendAttributes} class
   */
   @Nonnull public AmendAttributes amendmentReason(@Nonnull final String amendmentReason) {
    this.amendmentReason = amendmentReason;
    return this;
  }

   /**
   * Get amendmentReason
   * @return amendmentReason  The amendmentReason of this {@link AmendAttributes} instance.
  **/
  @Nonnull public String getAmendmentReason() {
    return amendmentReason;
  }

  /**
  * Set the amendmentReason of this {@link AmendAttributes} instance.
  *
  * @param amendmentReason  The amendmentReason of this {@link AmendAttributes}
  */
  public void setAmendmentReason( @Nonnull final String amendmentReason) {
    this.amendmentReason = amendmentReason;
  }

   /**
   * Set the isTemplateUpgradeRequired of this {@link AmendAttributes} instance and return the same instance.
   *
   * @param isTemplateUpgradeRequired  The isTemplateUpgradeRequired of this {@link AmendAttributes}
   * @return The same instance of this {@link AmendAttributes} class
   */
   @Nonnull public AmendAttributes isTemplateUpgradeRequired(@Nonnull final Boolean isTemplateUpgradeRequired) {
    this.isTemplateUpgradeRequired = isTemplateUpgradeRequired;
    return this;
  }

   /**
   * Get isTemplateUpgradeRequired
   * @return isTemplateUpgradeRequired  The isTemplateUpgradeRequired of this {@link AmendAttributes} instance.
  **/
  @Nonnull public Boolean isIsTemplateUpgradeRequired() {
    return isTemplateUpgradeRequired;
  }

  /**
  * Set the isTemplateUpgradeRequired of this {@link AmendAttributes} instance.
  *
  * @param isTemplateUpgradeRequired  The isTemplateUpgradeRequired of this {@link AmendAttributes}
  */
  public void setIsTemplateUpgradeRequired( @Nonnull final Boolean isTemplateUpgradeRequired) {
    this.isTemplateUpgradeRequired = isTemplateUpgradeRequired;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link AmendAttributes}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link AmendAttributes}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("AmendAttributes has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final AmendAttributes amendAttributes = (AmendAttributes) o;
    return Objects.equals(this.cloudSdkCustomFields, amendAttributes.cloudSdkCustomFields) &&
        Objects.equals(this.amendmentType, amendAttributes.amendmentType) &&
        Objects.equals(this.amendmentReason, amendAttributes.amendmentReason) &&
        Objects.equals(this.isTemplateUpgradeRequired, amendAttributes.isTemplateUpgradeRequired);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amendmentType, amendmentReason, isTemplateUpgradeRequired, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class AmendAttributes {\n");
    sb.append("    amendmentType: ").append(toIndentedString(amendmentType)).append("\n");
    sb.append("    amendmentReason: ").append(toIndentedString(amendmentReason)).append("\n");
    sb.append("    isTemplateUpgradeRequired: ").append(toIndentedString(isTemplateUpgradeRequired)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

