

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * MoneyDifference
 */

// CHECKSTYLE:OFF
public class MoneyDifference 
// CHECKSTYLE:ON
{
  @JsonProperty("difference")
  private String difference;

  @JsonProperty("percentage")
  private BigDecimal percentage;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the difference of this {@link MoneyDifference} instance and return the same instance.
   *
   * @param difference  The difference of this {@link MoneyDifference}
   * @return The same instance of this {@link MoneyDifference} class
   */
   @Nonnull public MoneyDifference difference(@Nonnull final String difference) {
    this.difference = difference;
    return this;
  }

   /**
   * Get difference
   * @return difference  The difference of this {@link MoneyDifference} instance.
  **/
  @Nonnull public String getDifference() {
    return difference;
  }

  /**
  * Set the difference of this {@link MoneyDifference} instance.
  *
  * @param difference  The difference of this {@link MoneyDifference}
  */
  public void setDifference( @Nonnull final String difference) {
    this.difference = difference;
  }

   /**
   * Set the percentage of this {@link MoneyDifference} instance and return the same instance.
   *
   * @param percentage  The percentage of this {@link MoneyDifference}
   * @return The same instance of this {@link MoneyDifference} class
   */
   @Nonnull public MoneyDifference percentage(@Nonnull final BigDecimal percentage) {
    this.percentage = percentage;
    return this;
  }

   /**
   * Get percentage
   * @return percentage  The percentage of this {@link MoneyDifference} instance.
  **/
  @Nonnull public BigDecimal getPercentage() {
    return percentage;
  }

  /**
  * Set the percentage of this {@link MoneyDifference} instance.
  *
  * @param percentage  The percentage of this {@link MoneyDifference}
  */
  public void setPercentage( @Nonnull final BigDecimal percentage) {
    this.percentage = percentage;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link MoneyDifference}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link MoneyDifference}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("MoneyDifference has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final MoneyDifference moneyDifference = (MoneyDifference) o;
    return Objects.equals(this.cloudSdkCustomFields, moneyDifference.cloudSdkCustomFields) &&
        Objects.equals(this.difference, moneyDifference.difference) &&
        Objects.equals(this.percentage, moneyDifference.percentage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(difference, percentage, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class MoneyDifference {\n");
    sb.append("    difference: ").append(toIndentedString(difference)).append("\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

