

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * PercentType
 */

// CHECKSTYLE:OFF
public class PercentType 
// CHECKSTYLE:ON
{
  @JsonProperty("percentValue")
  private BigDecimal percentValue;

  @JsonProperty("scale")
  private BigDecimal scale;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the percentValue of this {@link PercentType} instance and return the same instance.
   *
   * @param percentValue  The percentValue of this {@link PercentType}
   * @return The same instance of this {@link PercentType} class
   */
   @Nonnull public PercentType percentValue(@Nonnull final BigDecimal percentValue) {
    this.percentValue = percentValue;
    return this;
  }

   /**
   * Get percentValue
   * @return percentValue  The percentValue of this {@link PercentType} instance.
  **/
  @Nonnull public BigDecimal getPercentValue() {
    return percentValue;
  }

  /**
  * Set the percentValue of this {@link PercentType} instance.
  *
  * @param percentValue  The percentValue of this {@link PercentType}
  */
  public void setPercentValue( @Nonnull final BigDecimal percentValue) {
    this.percentValue = percentValue;
  }

   /**
   * Set the scale of this {@link PercentType} instance and return the same instance.
   *
   * @param scale  The scale of this {@link PercentType}
   * @return The same instance of this {@link PercentType} class
   */
   @Nonnull public PercentType scale(@Nonnull final BigDecimal scale) {
    this.scale = scale;
    return this;
  }

   /**
   * Get scale
   * @return scale  The scale of this {@link PercentType} instance.
  **/
  @Nonnull public BigDecimal getScale() {
    return scale;
  }

  /**
  * Set the scale of this {@link PercentType} instance.
  *
  * @param scale  The scale of this {@link PercentType}
  */
  public void setScale( @Nonnull final BigDecimal scale) {
    this.scale = scale;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link PercentType}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link PercentType}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("PercentType has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final PercentType percentType = (PercentType) o;
    return Objects.equals(this.cloudSdkCustomFields, percentType.cloudSdkCustomFields) &&
        Objects.equals(this.percentValue, percentType.percentValue) &&
        Objects.equals(this.scale, percentType.scale);
  }

  @Override
  public int hashCode() {
    return Objects.hash(percentValue, scale, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class PercentType {\n");
    sb.append("    percentValue: ").append(toIndentedString(percentValue)).append("\n");
    sb.append("    scale: ").append(toIndentedString(scale)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

