

/*
 * Contract Terms Management API
 * This Contract Terms Management allows a client application to : - create a contract term in the specified contract workspace and a contract request for the corresponding compliance contract in the specified buyer realm. The API creates the Contract Terms Document in the specified contract workspace and then, calls the Compliance Contract Request API using the Contract Terms Document ID  and the buyer realm name as input. If the Compliance Contract Request Object is successfully created, then the API returns the ACC Contract Request ID to the client; otherwise, it sends an error message to the client. - retrieve details including contract term ID, contract request ID and contract ID for the specified contract workspace ID. The response contains the contract terms document details like title, owner, status etc and the compliance contract request details like Contract Request ID (CRID), Contract ID (CID), etc. associated with the contract workspace. - synchronize the contract line item information of a contract workspace with the linked compliance contract by specifying the IDs of the contract workspace and the compliance contract. If the request is successful, the API initiates an asynchronous job and returns the job ID for reference.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.ct.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * ContractTerms
 */

// CHECKSTYLE:OFF
public class ContractTerms 
// CHECKSTYLE:ON
{
  @JsonProperty("title")
  private String title;

  @JsonProperty("documentId")
  private String documentId;

  @JsonProperty("version")
  private String version;

  @JsonProperty("owner")
  private String owner;

  @JsonProperty("status")
  private String status;

  @JsonProperty("lastModifiedDate")
  private String lastModifiedDate;

  @JsonProperty("creationDate")
  private String creationDate;

  @JsonProperty("sspContractId")
  private String sspContractId;

  @JsonProperty("sspContractStatus")
  private String sspContractStatus;

  @JsonProperty("sspContractRequestId")
  private String sspContractRequestId;

  @JsonProperty("sspContractRequestStatus")
  private String sspContractRequestStatus;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the title of this {@link ContractTerms} instance and return the same instance.
   *
   * @param title  Title of the contract terms document in the contract workspace
   * @return The same instance of this {@link ContractTerms} class
   */
   @Nonnull public ContractTerms title(@Nonnull final String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of the contract terms document in the contract workspace
   * @return title  The title of this {@link ContractTerms} instance.
  **/
  @Nonnull public String getTitle() {
    return title;
  }

  /**
  * Set the title of this {@link ContractTerms} instance.
  *
  * @param title  Title of the contract terms document in the contract workspace
  */
  public void setTitle( @Nonnull final String title) {
    this.title = title;
  }

   /**
   * Set the documentId of this {@link ContractTerms} instance and return the same instance.
   *
   * @param documentId  ID of the contract terms document in the contract workspace
   * @return The same instance of this {@link ContractTerms} class
   */
   @Nonnull public ContractTerms documentId(@Nonnull final String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * ID of the contract terms document in the contract workspace
   * @return documentId  The documentId of this {@link ContractTerms} instance.
  **/
  @Nonnull public String getDocumentId() {
    return documentId;
  }

  /**
  * Set the documentId of this {@link ContractTerms} instance.
  *
  * @param documentId  ID of the contract terms document in the contract workspace
  */
  public void setDocumentId( @Nonnull final String documentId) {
    this.documentId = documentId;
  }

   /**
   * Set the version of this {@link ContractTerms} instance and return the same instance.
   *
   * @param version  Version of the contract terms document in the contract workspace
   * @return The same instance of this {@link ContractTerms} class
   */
   @Nonnull public ContractTerms version(@Nonnull final String version) {
    this.version = version;
    return this;
  }

   /**
   * Version of the contract terms document in the contract workspace
   * @return version  The version of this {@link ContractTerms} instance.
  **/
  @Nonnull public String getVersion() {
    return version;
  }

  /**
  * Set the version of this {@link ContractTerms} instance.
  *
  * @param version  Version of the contract terms document in the contract workspace
  */
  public void setVersion( @Nonnull final String version) {
    this.version = version;
  }

   /**
   * Set the owner of this {@link ContractTerms} instance and return the same instance.
   *
   * @param owner  Owner of the contract terms document in the contract workspace
   * @return The same instance of this {@link ContractTerms} class
   */
   @Nonnull public ContractTerms owner(@Nonnull final String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Owner of the contract terms document in the contract workspace
   * @return owner  The owner of this {@link ContractTerms} instance.
  **/
  @Nonnull public String getOwner() {
    return owner;
  }

  /**
  * Set the owner of this {@link ContractTerms} instance.
  *
  * @param owner  Owner of the contract terms document in the contract workspace
  */
  public void setOwner( @Nonnull final String owner) {
    this.owner = owner;
  }

   /**
   * Set the status of this {@link ContractTerms} instance and return the same instance.
   *
   * @param status  Status of the contract terms document in the contract workspace
   * @return The same instance of this {@link ContractTerms} class
   */
   @Nonnull public ContractTerms status(@Nonnull final String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the contract terms document in the contract workspace
   * @return status  The status of this {@link ContractTerms} instance.
  **/
  @Nonnull public String getStatus() {
    return status;
  }

  /**
  * Set the status of this {@link ContractTerms} instance.
  *
  * @param status  Status of the contract terms document in the contract workspace
  */
  public void setStatus( @Nonnull final String status) {
    this.status = status;
  }

   /**
   * Set the lastModifiedDate of this {@link ContractTerms} instance and return the same instance.
   *
   * @param lastModifiedDate  The last modified date of the contract terms document in the contract workspace
   * @return The same instance of this {@link ContractTerms} class
   */
   @Nonnull public ContractTerms lastModifiedDate(@Nonnull final String lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * The last modified date of the contract terms document in the contract workspace
   * @return lastModifiedDate  The lastModifiedDate of this {@link ContractTerms} instance.
  **/
  @Nonnull public String getLastModifiedDate() {
    return lastModifiedDate;
  }

  /**
  * Set the lastModifiedDate of this {@link ContractTerms} instance.
  *
  * @param lastModifiedDate  The last modified date of the contract terms document in the contract workspace
  */
  public void setLastModifiedDate( @Nonnull final String lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

   /**
   * Set the creationDate of this {@link ContractTerms} instance and return the same instance.
   *
   * @param creationDate  The creation date of the contract terms document in the contract workspace
   * @return The same instance of this {@link ContractTerms} class
   */
   @Nonnull public ContractTerms creationDate(@Nonnull final String creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * The creation date of the contract terms document in the contract workspace
   * @return creationDate  The creationDate of this {@link ContractTerms} instance.
  **/
  @Nonnull public String getCreationDate() {
    return creationDate;
  }

  /**
  * Set the creationDate of this {@link ContractTerms} instance.
  *
  * @param creationDate  The creation date of the contract terms document in the contract workspace
  */
  public void setCreationDate( @Nonnull final String creationDate) {
    this.creationDate = creationDate;
  }

   /**
   * Set the sspContractId of this {@link ContractTerms} instance and return the same instance.
   *
   * @param sspContractId  Contract ID (CID) of the compliance contract associated with the contract terms document
   * @return The same instance of this {@link ContractTerms} class
   */
   @Nonnull public ContractTerms sspContractId(@Nonnull final String sspContractId) {
    this.sspContractId = sspContractId;
    return this;
  }

   /**
   * Contract ID (CID) of the compliance contract associated with the contract terms document
   * @return sspContractId  The sspContractId of this {@link ContractTerms} instance.
  **/
  @Nonnull public String getSspContractId() {
    return sspContractId;
  }

  /**
  * Set the sspContractId of this {@link ContractTerms} instance.
  *
  * @param sspContractId  Contract ID (CID) of the compliance contract associated with the contract terms document
  */
  public void setSspContractId( @Nonnull final String sspContractId) {
    this.sspContractId = sspContractId;
  }

   /**
   * Set the sspContractStatus of this {@link ContractTerms} instance and return the same instance.
   *
   * @param sspContractStatus  The status of the compliance contract associated with the contract terms document
   * @return The same instance of this {@link ContractTerms} class
   */
   @Nonnull public ContractTerms sspContractStatus(@Nonnull final String sspContractStatus) {
    this.sspContractStatus = sspContractStatus;
    return this;
  }

   /**
   * The status of the compliance contract associated with the contract terms document
   * @return sspContractStatus  The sspContractStatus of this {@link ContractTerms} instance.
  **/
  @Nonnull public String getSspContractStatus() {
    return sspContractStatus;
  }

  /**
  * Set the sspContractStatus of this {@link ContractTerms} instance.
  *
  * @param sspContractStatus  The status of the compliance contract associated with the contract terms document
  */
  public void setSspContractStatus( @Nonnull final String sspContractStatus) {
    this.sspContractStatus = sspContractStatus;
  }

   /**
   * Set the sspContractRequestId of this {@link ContractTerms} instance and return the same instance.
   *
   * @param sspContractRequestId  The contract request ID (CRID) of the compliance contract request associated with the contract terms document
   * @return The same instance of this {@link ContractTerms} class
   */
   @Nonnull public ContractTerms sspContractRequestId(@Nonnull final String sspContractRequestId) {
    this.sspContractRequestId = sspContractRequestId;
    return this;
  }

   /**
   * The contract request ID (CRID) of the compliance contract request associated with the contract terms document
   * @return sspContractRequestId  The sspContractRequestId of this {@link ContractTerms} instance.
  **/
  @Nonnull public String getSspContractRequestId() {
    return sspContractRequestId;
  }

  /**
  * Set the sspContractRequestId of this {@link ContractTerms} instance.
  *
  * @param sspContractRequestId  The contract request ID (CRID) of the compliance contract request associated with the contract terms document
  */
  public void setSspContractRequestId( @Nonnull final String sspContractRequestId) {
    this.sspContractRequestId = sspContractRequestId;
  }

   /**
   * Set the sspContractRequestStatus of this {@link ContractTerms} instance and return the same instance.
   *
   * @param sspContractRequestStatus  The status of the compliance contract request associated with the contract terms document
   * @return The same instance of this {@link ContractTerms} class
   */
   @Nonnull public ContractTerms sspContractRequestStatus(@Nonnull final String sspContractRequestStatus) {
    this.sspContractRequestStatus = sspContractRequestStatus;
    return this;
  }

   /**
   * The status of the compliance contract request associated with the contract terms document
   * @return sspContractRequestStatus  The sspContractRequestStatus of this {@link ContractTerms} instance.
  **/
  @Nonnull public String getSspContractRequestStatus() {
    return sspContractRequestStatus;
  }

  /**
  * Set the sspContractRequestStatus of this {@link ContractTerms} instance.
  *
  * @param sspContractRequestStatus  The status of the compliance contract request associated with the contract terms document
  */
  public void setSspContractRequestStatus( @Nonnull final String sspContractRequestStatus) {
    this.sspContractRequestStatus = sspContractRequestStatus;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link ContractTerms}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link ContractTerms}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("ContractTerms has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ContractTerms contractTerms = (ContractTerms) o;
    return Objects.equals(this.cloudSdkCustomFields, contractTerms.cloudSdkCustomFields) &&
        Objects.equals(this.title, contractTerms.title) &&
        Objects.equals(this.documentId, contractTerms.documentId) &&
        Objects.equals(this.version, contractTerms.version) &&
        Objects.equals(this.owner, contractTerms.owner) &&
        Objects.equals(this.status, contractTerms.status) &&
        Objects.equals(this.lastModifiedDate, contractTerms.lastModifiedDate) &&
        Objects.equals(this.creationDate, contractTerms.creationDate) &&
        Objects.equals(this.sspContractId, contractTerms.sspContractId) &&
        Objects.equals(this.sspContractStatus, contractTerms.sspContractStatus) &&
        Objects.equals(this.sspContractRequestId, contractTerms.sspContractRequestId) &&
        Objects.equals(this.sspContractRequestStatus, contractTerms.sspContractRequestStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, documentId, version, owner, status, lastModifiedDate, creationDate, sspContractId, sspContractStatus, sspContractRequestId, sspContractRequestStatus, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ContractTerms {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    sspContractId: ").append(toIndentedString(sspContractId)).append("\n");
    sb.append("    sspContractStatus: ").append(toIndentedString(sspContractStatus)).append("\n");
    sb.append("    sspContractRequestId: ").append(toIndentedString(sspContractRequestId)).append("\n");
    sb.append("    sspContractRequestStatus: ").append(toIndentedString(sspContractRequestStatus)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

