

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * User
 */

// CHECKSTYLE:OFF
public class User 
// CHECKSTYLE:ON
{
  @JsonProperty("uniqueName")
  private String uniqueName;

  @JsonProperty("passwordAdapter")
  private String passwordAdapter;

  @JsonProperty("name")
  private String name;

  @JsonProperty("emailAddress")
  private String emailAddress;

  @JsonProperty("phone")
  private String phone;

  @JsonProperty("networkUserId")
  private String networkUserId;

  @JsonProperty("networkPersonId")
  private String networkPersonId;

  @JsonProperty("organization")
  private String organization;

  @JsonProperty("orgANId")
  private String orgANId;

  @JsonProperty("orgName")
  private String orgName;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the uniqueName of this {@link User} instance and return the same instance.
   *
   * @param uniqueName  The uniqueName of this {@link User}
   * @return The same instance of this {@link User} class
   */
   @Nonnull public User uniqueName(@Nonnull final String uniqueName) {
    this.uniqueName = uniqueName;
    return this;
  }

   /**
   * Get uniqueName
   * @return uniqueName  The uniqueName of this {@link User} instance.
  **/
  @Nonnull public String getUniqueName() {
    return uniqueName;
  }

  /**
  * Set the uniqueName of this {@link User} instance.
  *
  * @param uniqueName  The uniqueName of this {@link User}
  */
  public void setUniqueName( @Nonnull final String uniqueName) {
    this.uniqueName = uniqueName;
  }

   /**
   * Set the passwordAdapter of this {@link User} instance and return the same instance.
   *
   * @param passwordAdapter  The passwordAdapter of this {@link User}
   * @return The same instance of this {@link User} class
   */
   @Nonnull public User passwordAdapter(@Nonnull final String passwordAdapter) {
    this.passwordAdapter = passwordAdapter;
    return this;
  }

   /**
   * Get passwordAdapter
   * @return passwordAdapter  The passwordAdapter of this {@link User} instance.
  **/
  @Nonnull public String getPasswordAdapter() {
    return passwordAdapter;
  }

  /**
  * Set the passwordAdapter of this {@link User} instance.
  *
  * @param passwordAdapter  The passwordAdapter of this {@link User}
  */
  public void setPasswordAdapter( @Nonnull final String passwordAdapter) {
    this.passwordAdapter = passwordAdapter;
  }

   /**
   * Set the name of this {@link User} instance and return the same instance.
   *
   * @param name  The name of this {@link User}
   * @return The same instance of this {@link User} class
   */
   @Nonnull public User name(@Nonnull final String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name  The name of this {@link User} instance.
  **/
  @Nonnull public String getName() {
    return name;
  }

  /**
  * Set the name of this {@link User} instance.
  *
  * @param name  The name of this {@link User}
  */
  public void setName( @Nonnull final String name) {
    this.name = name;
  }

   /**
   * Set the emailAddress of this {@link User} instance and return the same instance.
   *
   * @param emailAddress  The emailAddress of this {@link User}
   * @return The same instance of this {@link User} class
   */
   @Nonnull public User emailAddress(@Nonnull final String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Get emailAddress
   * @return emailAddress  The emailAddress of this {@link User} instance.
  **/
  @Nonnull public String getEmailAddress() {
    return emailAddress;
  }

  /**
  * Set the emailAddress of this {@link User} instance.
  *
  * @param emailAddress  The emailAddress of this {@link User}
  */
  public void setEmailAddress( @Nonnull final String emailAddress) {
    this.emailAddress = emailAddress;
  }

   /**
   * Set the phone of this {@link User} instance and return the same instance.
   *
   * @param phone  The phone of this {@link User}
   * @return The same instance of this {@link User} class
   */
   @Nonnull public User phone(@Nonnull final String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone  The phone of this {@link User} instance.
  **/
  @Nonnull public String getPhone() {
    return phone;
  }

  /**
  * Set the phone of this {@link User} instance.
  *
  * @param phone  The phone of this {@link User}
  */
  public void setPhone( @Nonnull final String phone) {
    this.phone = phone;
  }

   /**
   * Set the networkUserId of this {@link User} instance and return the same instance.
   *
   * @param networkUserId  The networkUserId of this {@link User}
   * @return The same instance of this {@link User} class
   */
   @Nonnull public User networkUserId(@Nonnull final String networkUserId) {
    this.networkUserId = networkUserId;
    return this;
  }

   /**
   * Get networkUserId
   * @return networkUserId  The networkUserId of this {@link User} instance.
  **/
  @Nonnull public String getNetworkUserId() {
    return networkUserId;
  }

  /**
  * Set the networkUserId of this {@link User} instance.
  *
  * @param networkUserId  The networkUserId of this {@link User}
  */
  public void setNetworkUserId( @Nonnull final String networkUserId) {
    this.networkUserId = networkUserId;
  }

   /**
   * Set the networkPersonId of this {@link User} instance and return the same instance.
   *
   * @param networkPersonId  The networkPersonId of this {@link User}
   * @return The same instance of this {@link User} class
   */
   @Nonnull public User networkPersonId(@Nonnull final String networkPersonId) {
    this.networkPersonId = networkPersonId;
    return this;
  }

   /**
   * Get networkPersonId
   * @return networkPersonId  The networkPersonId of this {@link User} instance.
  **/
  @Nonnull public String getNetworkPersonId() {
    return networkPersonId;
  }

  /**
  * Set the networkPersonId of this {@link User} instance.
  *
  * @param networkPersonId  The networkPersonId of this {@link User}
  */
  public void setNetworkPersonId( @Nonnull final String networkPersonId) {
    this.networkPersonId = networkPersonId;
  }

   /**
   * Set the organization of this {@link User} instance and return the same instance.
   *
   * @param organization  The organization of this {@link User}
   * @return The same instance of this {@link User} class
   */
   @Nonnull public User organization(@Nonnull final String organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization  The organization of this {@link User} instance.
  **/
  @Nonnull public String getOrganization() {
    return organization;
  }

  /**
  * Set the organization of this {@link User} instance.
  *
  * @param organization  The organization of this {@link User}
  */
  public void setOrganization( @Nonnull final String organization) {
    this.organization = organization;
  }

   /**
   * Set the orgANId of this {@link User} instance and return the same instance.
   *
   * @param orgANId  The orgANId of this {@link User}
   * @return The same instance of this {@link User} class
   */
   @Nonnull public User orgANId(@Nonnull final String orgANId) {
    this.orgANId = orgANId;
    return this;
  }

   /**
   * Get orgANId
   * @return orgANId  The orgANId of this {@link User} instance.
  **/
  @Nonnull public String getOrgANId() {
    return orgANId;
  }

  /**
  * Set the orgANId of this {@link User} instance.
  *
  * @param orgANId  The orgANId of this {@link User}
  */
  public void setOrgANId( @Nonnull final String orgANId) {
    this.orgANId = orgANId;
  }

   /**
   * Set the orgName of this {@link User} instance and return the same instance.
   *
   * @param orgName  The orgName of this {@link User}
   * @return The same instance of this {@link User} class
   */
   @Nonnull public User orgName(@Nonnull final String orgName) {
    this.orgName = orgName;
    return this;
  }

   /**
   * Get orgName
   * @return orgName  The orgName of this {@link User} instance.
  **/
  @Nonnull public String getOrgName() {
    return orgName;
  }

  /**
  * Set the orgName of this {@link User} instance.
  *
  * @param orgName  The orgName of this {@link User}
  */
  public void setOrgName( @Nonnull final String orgName) {
    this.orgName = orgName;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link User}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link User}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("User has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final User user = (User) o;
    return Objects.equals(this.cloudSdkCustomFields, user.cloudSdkCustomFields) &&
        Objects.equals(this.uniqueName, user.uniqueName) &&
        Objects.equals(this.passwordAdapter, user.passwordAdapter) &&
        Objects.equals(this.name, user.name) &&
        Objects.equals(this.emailAddress, user.emailAddress) &&
        Objects.equals(this.phone, user.phone) &&
        Objects.equals(this.networkUserId, user.networkUserId) &&
        Objects.equals(this.networkPersonId, user.networkPersonId) &&
        Objects.equals(this.organization, user.organization) &&
        Objects.equals(this.orgANId, user.orgANId) &&
        Objects.equals(this.orgName, user.orgName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uniqueName, passwordAdapter, name, emailAddress, phone, networkUserId, networkPersonId, organization, orgANId, orgName, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    sb.append("    uniqueName: ").append(toIndentedString(uniqueName)).append("\n");
    sb.append("    passwordAdapter: ").append(toIndentedString(passwordAdapter)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    networkUserId: ").append(toIndentedString(networkUserId)).append("\n");
    sb.append("    networkPersonId: ").append(toIndentedString(networkPersonId)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    orgANId: ").append(toIndentedString(orgANId)).append("\n");
    sb.append("    orgName: ").append(toIndentedString(orgName)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

