

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Commodity
 */

// CHECKSTYLE:OFF
public class Commodity 
// CHECKSTYLE:ON
{
  @JsonProperty("uniqueName")
  private String uniqueName;

  @JsonProperty("domain")
  private String domain;

  @JsonProperty("name")
  private String name;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the uniqueName of this {@link Commodity} instance and return the same instance.
   *
   * @param uniqueName  The uniqueName of this {@link Commodity}
   * @return The same instance of this {@link Commodity} class
   */
   @Nonnull public Commodity uniqueName(@Nonnull final String uniqueName) {
    this.uniqueName = uniqueName;
    return this;
  }

   /**
   * Get uniqueName
   * @return uniqueName  The uniqueName of this {@link Commodity} instance.
  **/
  @Nonnull public String getUniqueName() {
    return uniqueName;
  }

  /**
  * Set the uniqueName of this {@link Commodity} instance.
  *
  * @param uniqueName  The uniqueName of this {@link Commodity}
  */
  public void setUniqueName( @Nonnull final String uniqueName) {
    this.uniqueName = uniqueName;
  }

   /**
   * Set the domain of this {@link Commodity} instance and return the same instance.
   *
   * @param domain  The domain of this {@link Commodity}
   * @return The same instance of this {@link Commodity} class
   */
   @Nonnull public Commodity domain(@Nonnull final String domain) {
    this.domain = domain;
    return this;
  }

   /**
   * Get domain
   * @return domain  The domain of this {@link Commodity} instance.
  **/
  @Nonnull public String getDomain() {
    return domain;
  }

  /**
  * Set the domain of this {@link Commodity} instance.
  *
  * @param domain  The domain of this {@link Commodity}
  */
  public void setDomain( @Nonnull final String domain) {
    this.domain = domain;
  }

   /**
   * Set the name of this {@link Commodity} instance and return the same instance.
   *
   * @param name  The name of this {@link Commodity}
   * @return The same instance of this {@link Commodity} class
   */
   @Nonnull public Commodity name(@Nonnull final String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name  The name of this {@link Commodity} instance.
  **/
  @Nonnull public String getName() {
    return name;
  }

  /**
  * Set the name of this {@link Commodity} instance.
  *
  * @param name  The name of this {@link Commodity}
  */
  public void setName( @Nonnull final String name) {
    this.name = name;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link Commodity}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link Commodity}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("Commodity has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final Commodity commodity = (Commodity) o;
    return Objects.equals(this.cloudSdkCustomFields, commodity.cloudSdkCustomFields) &&
        Objects.equals(this.uniqueName, commodity.uniqueName) &&
        Objects.equals(this.domain, commodity.domain) &&
        Objects.equals(this.name, commodity.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uniqueName, domain, name, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class Commodity {\n");
    sb.append("    uniqueName: ").append(toIndentedString(uniqueName)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

