

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * ContractWorkspaceActionResponse
 */

// CHECKSTYLE:OFF
public class ContractWorkspaceActionResponse 
// CHECKSTYLE:ON
{
  @JsonProperty("contractId")
  private String contractId;

  @JsonProperty("contractStatus")
  private String contractStatus;

  @JsonProperty("version")
  private Long version;

  @JsonProperty("displayVersion")
  private String displayVersion;

  @JsonProperty("warnings")
  private List<String> warnings = new ArrayList<>();

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the contractId of this {@link ContractWorkspaceActionResponse} instance and return the same instance.
   *
   * @param contractId  The contractId of this {@link ContractWorkspaceActionResponse}
   * @return The same instance of this {@link ContractWorkspaceActionResponse} class
   */
   @Nonnull public ContractWorkspaceActionResponse contractId(@Nonnull final String contractId) {
    this.contractId = contractId;
    return this;
  }

   /**
   * Get contractId
   * @return contractId  The contractId of this {@link ContractWorkspaceActionResponse} instance.
  **/
  @Nonnull public String getContractId() {
    return contractId;
  }

  /**
  * Set the contractId of this {@link ContractWorkspaceActionResponse} instance.
  *
  * @param contractId  The contractId of this {@link ContractWorkspaceActionResponse}
  */
  public void setContractId( @Nonnull final String contractId) {
    this.contractId = contractId;
  }

   /**
   * Set the contractStatus of this {@link ContractWorkspaceActionResponse} instance and return the same instance.
   *
   * @param contractStatus  The contractStatus of this {@link ContractWorkspaceActionResponse}
   * @return The same instance of this {@link ContractWorkspaceActionResponse} class
   */
   @Nonnull public ContractWorkspaceActionResponse contractStatus(@Nonnull final String contractStatus) {
    this.contractStatus = contractStatus;
    return this;
  }

   /**
   * Get contractStatus
   * @return contractStatus  The contractStatus of this {@link ContractWorkspaceActionResponse} instance.
  **/
  @Nonnull public String getContractStatus() {
    return contractStatus;
  }

  /**
  * Set the contractStatus of this {@link ContractWorkspaceActionResponse} instance.
  *
  * @param contractStatus  The contractStatus of this {@link ContractWorkspaceActionResponse}
  */
  public void setContractStatus( @Nonnull final String contractStatus) {
    this.contractStatus = contractStatus;
  }

   /**
   * Set the version of this {@link ContractWorkspaceActionResponse} instance and return the same instance.
   *
   * @param version  The version of this {@link ContractWorkspaceActionResponse}
   * @return The same instance of this {@link ContractWorkspaceActionResponse} class
   */
   @Nonnull public ContractWorkspaceActionResponse version(@Nonnull final Long version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version  The version of this {@link ContractWorkspaceActionResponse} instance.
  **/
  @Nonnull public Long getVersion() {
    return version;
  }

  /**
  * Set the version of this {@link ContractWorkspaceActionResponse} instance.
  *
  * @param version  The version of this {@link ContractWorkspaceActionResponse}
  */
  public void setVersion( @Nonnull final Long version) {
    this.version = version;
  }

   /**
   * Set the displayVersion of this {@link ContractWorkspaceActionResponse} instance and return the same instance.
   *
   * @param displayVersion  The displayVersion of this {@link ContractWorkspaceActionResponse}
   * @return The same instance of this {@link ContractWorkspaceActionResponse} class
   */
   @Nonnull public ContractWorkspaceActionResponse displayVersion(@Nonnull final String displayVersion) {
    this.displayVersion = displayVersion;
    return this;
  }

   /**
   * Get displayVersion
   * @return displayVersion  The displayVersion of this {@link ContractWorkspaceActionResponse} instance.
  **/
  @Nonnull public String getDisplayVersion() {
    return displayVersion;
  }

  /**
  * Set the displayVersion of this {@link ContractWorkspaceActionResponse} instance.
  *
  * @param displayVersion  The displayVersion of this {@link ContractWorkspaceActionResponse}
  */
  public void setDisplayVersion( @Nonnull final String displayVersion) {
    this.displayVersion = displayVersion;
  }

   /**
   * Set the warnings of this {@link ContractWorkspaceActionResponse} instance and return the same instance.
   *
   * @param warnings  The warnings of this {@link ContractWorkspaceActionResponse}
   * @return The same instance of this {@link ContractWorkspaceActionResponse} class
   */
   @Nonnull public ContractWorkspaceActionResponse warnings(@Nonnull final List<String> warnings) {
    this.warnings = warnings;
    return this;
  }
  /**
  * Add one Warnings instance to this {@link ContractWorkspaceActionResponse}.
  * @param warningsItem The Warnings that should be added
  * @return The same instance of type {@link ContractWorkspaceActionResponse}
  */
  @Nonnull public ContractWorkspaceActionResponse addWarningsItem( @Nonnull final String warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

   /**
   * Get warnings
   * @return warnings  The warnings of this {@link ContractWorkspaceActionResponse} instance.
  **/
  @Nonnull public List<String> getWarnings() {
    return warnings;
  }

  /**
  * Set the warnings of this {@link ContractWorkspaceActionResponse} instance.
  *
  * @param warnings  The warnings of this {@link ContractWorkspaceActionResponse}
  */
  public void setWarnings( @Nonnull final List<String> warnings) {
    this.warnings = warnings;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link ContractWorkspaceActionResponse}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link ContractWorkspaceActionResponse}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("ContractWorkspaceActionResponse has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ContractWorkspaceActionResponse contractWorkspaceActionResponse = (ContractWorkspaceActionResponse) o;
    return Objects.equals(this.cloudSdkCustomFields, contractWorkspaceActionResponse.cloudSdkCustomFields) &&
        Objects.equals(this.contractId, contractWorkspaceActionResponse.contractId) &&
        Objects.equals(this.contractStatus, contractWorkspaceActionResponse.contractStatus) &&
        Objects.equals(this.version, contractWorkspaceActionResponse.version) &&
        Objects.equals(this.displayVersion, contractWorkspaceActionResponse.displayVersion) &&
        Objects.equals(this.warnings, contractWorkspaceActionResponse.warnings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractId, contractStatus, version, displayVersion, warnings, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ContractWorkspaceActionResponse {\n");
    sb.append("    contractId: ").append(toIndentedString(contractId)).append("\n");
    sb.append("    contractStatus: ").append(toIndentedString(contractStatus)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    displayVersion: ").append(toIndentedString(displayVersion)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

