

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.cw.model.ContractWorkspace;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * ContractWorkspacesResponse
 */

// CHECKSTYLE:OFF
public class ContractWorkspacesResponse 
// CHECKSTYLE:ON
{
  @JsonProperty("start")
  private BigDecimal start;

  @JsonProperty("count")
  private BigDecimal count;

  @JsonProperty("value")
  private List<ContractWorkspace> value = new ArrayList<>();

  @JsonProperty("warnings")
  private List<String> warnings = new ArrayList<>();

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the start of this {@link ContractWorkspacesResponse} instance and return the same instance.
   *
   * @param start  The start of this {@link ContractWorkspacesResponse}
   * @return The same instance of this {@link ContractWorkspacesResponse} class
   */
   @Nonnull public ContractWorkspacesResponse start(@Nonnull final BigDecimal start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start  The start of this {@link ContractWorkspacesResponse} instance.
  **/
  @Nonnull public BigDecimal getStart() {
    return start;
  }

  /**
  * Set the start of this {@link ContractWorkspacesResponse} instance.
  *
  * @param start  The start of this {@link ContractWorkspacesResponse}
  */
  public void setStart( @Nonnull final BigDecimal start) {
    this.start = start;
  }

   /**
   * Set the count of this {@link ContractWorkspacesResponse} instance and return the same instance.
   *
   * @param count  The count of this {@link ContractWorkspacesResponse}
   * @return The same instance of this {@link ContractWorkspacesResponse} class
   */
   @Nonnull public ContractWorkspacesResponse count(@Nonnull final BigDecimal count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count  The count of this {@link ContractWorkspacesResponse} instance.
  **/
  @Nonnull public BigDecimal getCount() {
    return count;
  }

  /**
  * Set the count of this {@link ContractWorkspacesResponse} instance.
  *
  * @param count  The count of this {@link ContractWorkspacesResponse}
  */
  public void setCount( @Nonnull final BigDecimal count) {
    this.count = count;
  }

   /**
   * Set the value of this {@link ContractWorkspacesResponse} instance and return the same instance.
   *
   * @param value  The value of this {@link ContractWorkspacesResponse}
   * @return The same instance of this {@link ContractWorkspacesResponse} class
   */
   @Nonnull public ContractWorkspacesResponse value(@Nonnull final List<ContractWorkspace> value) {
    this.value = value;
    return this;
  }
  /**
  * Add one Value instance to this {@link ContractWorkspacesResponse}.
  * @param valueItem The Value that should be added
  * @return The same instance of type {@link ContractWorkspacesResponse}
  */
  @Nonnull public ContractWorkspacesResponse addValueItem( @Nonnull final ContractWorkspace valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<>();
    }
    this.value.add(valueItem);
    return this;
  }

   /**
   * Get value
   * @return value  The value of this {@link ContractWorkspacesResponse} instance.
  **/
  @Nonnull public List<ContractWorkspace> getValue() {
    return value;
  }

  /**
  * Set the value of this {@link ContractWorkspacesResponse} instance.
  *
  * @param value  The value of this {@link ContractWorkspacesResponse}
  */
  public void setValue( @Nonnull final List<ContractWorkspace> value) {
    this.value = value;
  }

   /**
   * Set the warnings of this {@link ContractWorkspacesResponse} instance and return the same instance.
   *
   * @param warnings  The warnings of this {@link ContractWorkspacesResponse}
   * @return The same instance of this {@link ContractWorkspacesResponse} class
   */
   @Nonnull public ContractWorkspacesResponse warnings(@Nonnull final List<String> warnings) {
    this.warnings = warnings;
    return this;
  }
  /**
  * Add one Warnings instance to this {@link ContractWorkspacesResponse}.
  * @param warningsItem The Warnings that should be added
  * @return The same instance of type {@link ContractWorkspacesResponse}
  */
  @Nonnull public ContractWorkspacesResponse addWarningsItem( @Nonnull final String warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

   /**
   * Get warnings
   * @return warnings  The warnings of this {@link ContractWorkspacesResponse} instance.
  **/
  @Nonnull public List<String> getWarnings() {
    return warnings;
  }

  /**
  * Set the warnings of this {@link ContractWorkspacesResponse} instance.
  *
  * @param warnings  The warnings of this {@link ContractWorkspacesResponse}
  */
  public void setWarnings( @Nonnull final List<String> warnings) {
    this.warnings = warnings;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link ContractWorkspacesResponse}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link ContractWorkspacesResponse}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("ContractWorkspacesResponse has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ContractWorkspacesResponse contractWorkspacesResponse = (ContractWorkspacesResponse) o;
    return Objects.equals(this.cloudSdkCustomFields, contractWorkspacesResponse.cloudSdkCustomFields) &&
        Objects.equals(this.start, contractWorkspacesResponse.start) &&
        Objects.equals(this.count, contractWorkspacesResponse.count) &&
        Objects.equals(this.value, contractWorkspacesResponse.value) &&
        Objects.equals(this.warnings, contractWorkspacesResponse.warnings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, count, value, warnings, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ContractWorkspacesResponse {\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

