

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.cw.model.Commodity;
import com.sap.openapi.cw.model.CustomField;
import com.sap.openapi.cw.model.Department;
import com.sap.openapi.cw.model.IntegratedSystemRef;
import com.sap.openapi.cw.model.Money;
import com.sap.openapi.cw.model.Organization;
import com.sap.openapi.cw.model.Question;
import com.sap.openapi.cw.model.Region;
import com.sap.openapi.cw.model.SupplierClassificationBean;
import com.sap.openapi.cw.model.User;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * ContractWorkspace
 */

// CHECKSTYLE:OFF
public class ContractWorkspace 
// CHECKSTYLE:ON
{
  @JsonProperty("title")
  private String title;

  @JsonProperty("description")
  private String description;

  @JsonProperty("commodities")
  private List<Commodity> commodities = new ArrayList<>();

  @JsonProperty("regions")
  private List<Region> regions = new ArrayList<>();

  @JsonProperty("departments")
  private List<Department> departments = new ArrayList<>();

  @JsonProperty("questions")
  private List<Question> questions = new ArrayList<>();

  @JsonProperty("owner")
  private User owner;

  @JsonProperty("eventInternalId")
  private String eventInternalId;

  @JsonProperty("eventTitle")
  private String eventTitle;

  @JsonProperty("contractId")
  private String contractId;

  @JsonProperty("internalId")
  private String internalId;

  @JsonProperty("contractStatus")
  private String contractStatus;

  @JsonProperty("isTestProject")
  private Boolean isTestProject;

  @JsonProperty("supplier")
  private Organization supplier;

  @JsonProperty("affectedParties")
  private List<Organization> affectedParties = new ArrayList<>();

  @JsonProperty("expirationTermType")
  private String expirationTermType;

  @JsonProperty("hierarchicalType")
  private String hierarchicalType;

  @JsonProperty("parentAgreement")
  private String parentAgreement;

  @JsonProperty("effectiveDate")
  private String effectiveDate;

  @JsonProperty("agreementDate")
  private String agreementDate;

  @JsonProperty("expirationDate")
  private String expirationDate;

  @JsonProperty("creationDate")
  private String creationDate;

  @JsonProperty("contractAmount")
  private Money contractAmount;

  @JsonProperty("proposedContractAmount")
  private Money proposedContractAmount;

  @JsonProperty("version")
  private Long version;

  @JsonProperty("maximumNumberOfRenewals")
  private Long maximumNumberOfRenewals;

  @JsonProperty("autoRenewalInterval")
  private Long autoRenewalInterval;

  @JsonProperty("templateId")
  private String templateId;

  @JsonProperty("businessSystemId")
  private String businessSystemId;

  @JsonProperty("amendmentType")
  private String amendmentType;

  @JsonProperty("amendmentReason")
  private String amendmentReason;

  @JsonProperty("origin")
  private Integer origin;

  @JsonProperty("contractCreationSupplierClassification")
  private List<SupplierClassificationBean> contractCreationSupplierClassification = new ArrayList<>();

  @JsonProperty("contractPublishingSupplierClassification")
  private List<SupplierClassificationBean> contractPublishingSupplierClassification = new ArrayList<>();

  @JsonProperty("contractIntegrationSupplierClassification")
  private List<SupplierClassificationBean> contractIntegrationSupplierClassification = new ArrayList<>();

  @JsonProperty("customFields")
  private List<CustomField> customFields = new ArrayList<>();

  @JsonProperty("relatedId")
  private String relatedId;

  @JsonProperty("accessControl")
  private List<String> accessControl = new ArrayList<>();

  @JsonProperty("lastModified")
  private String lastModified;

  @JsonProperty("active")
  private Boolean active;

  @JsonProperty("blockPublish")
  private Boolean blockPublish;

  @JsonProperty("integratedSystemRefs")
  private List<IntegratedSystemRef> integratedSystemRefs = new ArrayList<>();

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the title of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param title  The title of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace title(@Nonnull final String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title  The title of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getTitle() {
    return title;
  }

  /**
  * Set the title of this {@link ContractWorkspace} instance.
  *
  * @param title  The title of this {@link ContractWorkspace}
  */
  public void setTitle( @Nonnull final String title) {
    this.title = title;
  }

   /**
   * Set the description of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param description  The description of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace description(@Nonnull final String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description  The description of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getDescription() {
    return description;
  }

  /**
  * Set the description of this {@link ContractWorkspace} instance.
  *
  * @param description  The description of this {@link ContractWorkspace}
  */
  public void setDescription( @Nonnull final String description) {
    this.description = description;
  }

   /**
   * Set the commodities of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param commodities  The commodities of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace commodities(@Nonnull final List<Commodity> commodities) {
    this.commodities = commodities;
    return this;
  }
  /**
  * Add one Commodities instance to this {@link ContractWorkspace}.
  * @param commoditiesItem The Commodities that should be added
  * @return The same instance of type {@link ContractWorkspace}
  */
  @Nonnull public ContractWorkspace addCommoditiesItem( @Nonnull final Commodity commoditiesItem) {
    if (this.commodities == null) {
      this.commodities = new ArrayList<>();
    }
    this.commodities.add(commoditiesItem);
    return this;
  }

   /**
   * Get commodities
   * @return commodities  The commodities of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public List<Commodity> getCommodities() {
    return commodities;
  }

  /**
  * Set the commodities of this {@link ContractWorkspace} instance.
  *
  * @param commodities  The commodities of this {@link ContractWorkspace}
  */
  public void setCommodities( @Nonnull final List<Commodity> commodities) {
    this.commodities = commodities;
  }

   /**
   * Set the regions of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param regions  The regions of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace regions(@Nonnull final List<Region> regions) {
    this.regions = regions;
    return this;
  }
  /**
  * Add one Regions instance to this {@link ContractWorkspace}.
  * @param regionsItem The Regions that should be added
  * @return The same instance of type {@link ContractWorkspace}
  */
  @Nonnull public ContractWorkspace addRegionsItem( @Nonnull final Region regionsItem) {
    if (this.regions == null) {
      this.regions = new ArrayList<>();
    }
    this.regions.add(regionsItem);
    return this;
  }

   /**
   * Get regions
   * @return regions  The regions of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public List<Region> getRegions() {
    return regions;
  }

  /**
  * Set the regions of this {@link ContractWorkspace} instance.
  *
  * @param regions  The regions of this {@link ContractWorkspace}
  */
  public void setRegions( @Nonnull final List<Region> regions) {
    this.regions = regions;
  }

   /**
   * Set the departments of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param departments  The departments of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace departments(@Nonnull final List<Department> departments) {
    this.departments = departments;
    return this;
  }
  /**
  * Add one Departments instance to this {@link ContractWorkspace}.
  * @param departmentsItem The Departments that should be added
  * @return The same instance of type {@link ContractWorkspace}
  */
  @Nonnull public ContractWorkspace addDepartmentsItem( @Nonnull final Department departmentsItem) {
    if (this.departments == null) {
      this.departments = new ArrayList<>();
    }
    this.departments.add(departmentsItem);
    return this;
  }

   /**
   * Get departments
   * @return departments  The departments of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public List<Department> getDepartments() {
    return departments;
  }

  /**
  * Set the departments of this {@link ContractWorkspace} instance.
  *
  * @param departments  The departments of this {@link ContractWorkspace}
  */
  public void setDepartments( @Nonnull final List<Department> departments) {
    this.departments = departments;
  }

   /**
   * Set the questions of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param questions  The questions of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace questions(@Nonnull final List<Question> questions) {
    this.questions = questions;
    return this;
  }
  /**
  * Add one Questions instance to this {@link ContractWorkspace}.
  * @param questionsItem The Questions that should be added
  * @return The same instance of type {@link ContractWorkspace}
  */
  @Nonnull public ContractWorkspace addQuestionsItem( @Nonnull final Question questionsItem) {
    if (this.questions == null) {
      this.questions = new ArrayList<>();
    }
    this.questions.add(questionsItem);
    return this;
  }

   /**
   * Get questions
   * @return questions  The questions of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public List<Question> getQuestions() {
    return questions;
  }

  /**
  * Set the questions of this {@link ContractWorkspace} instance.
  *
  * @param questions  The questions of this {@link ContractWorkspace}
  */
  public void setQuestions( @Nonnull final List<Question> questions) {
    this.questions = questions;
  }

   /**
   * Set the owner of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param owner  The owner of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace owner(@Nonnull final User owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner  The owner of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public User getOwner() {
    return owner;
  }

  /**
  * Set the owner of this {@link ContractWorkspace} instance.
  *
  * @param owner  The owner of this {@link ContractWorkspace}
  */
  public void setOwner( @Nonnull final User owner) {
    this.owner = owner;
  }

   /**
   * Set the eventInternalId of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param eventInternalId  The eventInternalId of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace eventInternalId(@Nonnull final String eventInternalId) {
    this.eventInternalId = eventInternalId;
    return this;
  }

   /**
   * Get eventInternalId
   * @return eventInternalId  The eventInternalId of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getEventInternalId() {
    return eventInternalId;
  }

  /**
  * Set the eventInternalId of this {@link ContractWorkspace} instance.
  *
  * @param eventInternalId  The eventInternalId of this {@link ContractWorkspace}
  */
  public void setEventInternalId( @Nonnull final String eventInternalId) {
    this.eventInternalId = eventInternalId;
  }

   /**
   * Set the eventTitle of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param eventTitle  The eventTitle of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace eventTitle(@Nonnull final String eventTitle) {
    this.eventTitle = eventTitle;
    return this;
  }

   /**
   * Get eventTitle
   * @return eventTitle  The eventTitle of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getEventTitle() {
    return eventTitle;
  }

  /**
  * Set the eventTitle of this {@link ContractWorkspace} instance.
  *
  * @param eventTitle  The eventTitle of this {@link ContractWorkspace}
  */
  public void setEventTitle( @Nonnull final String eventTitle) {
    this.eventTitle = eventTitle;
  }

   /**
   * Set the contractId of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param contractId  The contractId of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace contractId(@Nonnull final String contractId) {
    this.contractId = contractId;
    return this;
  }

   /**
   * Get contractId
   * @return contractId  The contractId of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getContractId() {
    return contractId;
  }

  /**
  * Set the contractId of this {@link ContractWorkspace} instance.
  *
  * @param contractId  The contractId of this {@link ContractWorkspace}
  */
  public void setContractId( @Nonnull final String contractId) {
    this.contractId = contractId;
  }

   /**
   * Set the internalId of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param internalId  The internalId of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace internalId(@Nonnull final String internalId) {
    this.internalId = internalId;
    return this;
  }

   /**
   * Get internalId
   * @return internalId  The internalId of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getInternalId() {
    return internalId;
  }

  /**
  * Set the internalId of this {@link ContractWorkspace} instance.
  *
  * @param internalId  The internalId of this {@link ContractWorkspace}
  */
  public void setInternalId( @Nonnull final String internalId) {
    this.internalId = internalId;
  }

   /**
   * Set the contractStatus of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param contractStatus  The contractStatus of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace contractStatus(@Nonnull final String contractStatus) {
    this.contractStatus = contractStatus;
    return this;
  }

   /**
   * Get contractStatus
   * @return contractStatus  The contractStatus of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getContractStatus() {
    return contractStatus;
  }

  /**
  * Set the contractStatus of this {@link ContractWorkspace} instance.
  *
  * @param contractStatus  The contractStatus of this {@link ContractWorkspace}
  */
  public void setContractStatus( @Nonnull final String contractStatus) {
    this.contractStatus = contractStatus;
  }

   /**
   * Set the isTestProject of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param isTestProject  The isTestProject of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace isTestProject(@Nonnull final Boolean isTestProject) {
    this.isTestProject = isTestProject;
    return this;
  }

   /**
   * Get isTestProject
   * @return isTestProject  The isTestProject of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public Boolean isIsTestProject() {
    return isTestProject;
  }

  /**
  * Set the isTestProject of this {@link ContractWorkspace} instance.
  *
  * @param isTestProject  The isTestProject of this {@link ContractWorkspace}
  */
  public void setIsTestProject( @Nonnull final Boolean isTestProject) {
    this.isTestProject = isTestProject;
  }

   /**
   * Set the supplier of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param supplier  The supplier of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace supplier(@Nonnull final Organization supplier) {
    this.supplier = supplier;
    return this;
  }

   /**
   * Get supplier
   * @return supplier  The supplier of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public Organization getSupplier() {
    return supplier;
  }

  /**
  * Set the supplier of this {@link ContractWorkspace} instance.
  *
  * @param supplier  The supplier of this {@link ContractWorkspace}
  */
  public void setSupplier( @Nonnull final Organization supplier) {
    this.supplier = supplier;
  }

   /**
   * Set the affectedParties of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param affectedParties  The affectedParties of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace affectedParties(@Nonnull final List<Organization> affectedParties) {
    this.affectedParties = affectedParties;
    return this;
  }
  /**
  * Add one AffectedParties instance to this {@link ContractWorkspace}.
  * @param affectedPartiesItem The AffectedParties that should be added
  * @return The same instance of type {@link ContractWorkspace}
  */
  @Nonnull public ContractWorkspace addAffectedPartiesItem( @Nonnull final Organization affectedPartiesItem) {
    if (this.affectedParties == null) {
      this.affectedParties = new ArrayList<>();
    }
    this.affectedParties.add(affectedPartiesItem);
    return this;
  }

   /**
   * Get affectedParties
   * @return affectedParties  The affectedParties of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public List<Organization> getAffectedParties() {
    return affectedParties;
  }

  /**
  * Set the affectedParties of this {@link ContractWorkspace} instance.
  *
  * @param affectedParties  The affectedParties of this {@link ContractWorkspace}
  */
  public void setAffectedParties( @Nonnull final List<Organization> affectedParties) {
    this.affectedParties = affectedParties;
  }

   /**
   * Set the expirationTermType of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param expirationTermType  The expirationTermType of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace expirationTermType(@Nonnull final String expirationTermType) {
    this.expirationTermType = expirationTermType;
    return this;
  }

   /**
   * Get expirationTermType
   * @return expirationTermType  The expirationTermType of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getExpirationTermType() {
    return expirationTermType;
  }

  /**
  * Set the expirationTermType of this {@link ContractWorkspace} instance.
  *
  * @param expirationTermType  The expirationTermType of this {@link ContractWorkspace}
  */
  public void setExpirationTermType( @Nonnull final String expirationTermType) {
    this.expirationTermType = expirationTermType;
  }

   /**
   * Set the hierarchicalType of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param hierarchicalType  The hierarchicalType of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace hierarchicalType(@Nonnull final String hierarchicalType) {
    this.hierarchicalType = hierarchicalType;
    return this;
  }

   /**
   * Get hierarchicalType
   * @return hierarchicalType  The hierarchicalType of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getHierarchicalType() {
    return hierarchicalType;
  }

  /**
  * Set the hierarchicalType of this {@link ContractWorkspace} instance.
  *
  * @param hierarchicalType  The hierarchicalType of this {@link ContractWorkspace}
  */
  public void setHierarchicalType( @Nonnull final String hierarchicalType) {
    this.hierarchicalType = hierarchicalType;
  }

   /**
   * Set the parentAgreement of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param parentAgreement  The parentAgreement of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace parentAgreement(@Nonnull final String parentAgreement) {
    this.parentAgreement = parentAgreement;
    return this;
  }

   /**
   * Get parentAgreement
   * @return parentAgreement  The parentAgreement of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getParentAgreement() {
    return parentAgreement;
  }

  /**
  * Set the parentAgreement of this {@link ContractWorkspace} instance.
  *
  * @param parentAgreement  The parentAgreement of this {@link ContractWorkspace}
  */
  public void setParentAgreement( @Nonnull final String parentAgreement) {
    this.parentAgreement = parentAgreement;
  }

   /**
   * Set the effectiveDate of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param effectiveDate  The effectiveDate of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace effectiveDate(@Nonnull final String effectiveDate) {
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * Get effectiveDate
   * @return effectiveDate  The effectiveDate of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getEffectiveDate() {
    return effectiveDate;
  }

  /**
  * Set the effectiveDate of this {@link ContractWorkspace} instance.
  *
  * @param effectiveDate  The effectiveDate of this {@link ContractWorkspace}
  */
  public void setEffectiveDate( @Nonnull final String effectiveDate) {
    this.effectiveDate = effectiveDate;
  }

   /**
   * Set the agreementDate of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param agreementDate  The agreementDate of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace agreementDate(@Nonnull final String agreementDate) {
    this.agreementDate = agreementDate;
    return this;
  }

   /**
   * Get agreementDate
   * @return agreementDate  The agreementDate of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getAgreementDate() {
    return agreementDate;
  }

  /**
  * Set the agreementDate of this {@link ContractWorkspace} instance.
  *
  * @param agreementDate  The agreementDate of this {@link ContractWorkspace}
  */
  public void setAgreementDate( @Nonnull final String agreementDate) {
    this.agreementDate = agreementDate;
  }

   /**
   * Set the expirationDate of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param expirationDate  The expirationDate of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace expirationDate(@Nonnull final String expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate  The expirationDate of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getExpirationDate() {
    return expirationDate;
  }

  /**
  * Set the expirationDate of this {@link ContractWorkspace} instance.
  *
  * @param expirationDate  The expirationDate of this {@link ContractWorkspace}
  */
  public void setExpirationDate( @Nonnull final String expirationDate) {
    this.expirationDate = expirationDate;
  }

   /**
   * Set the creationDate of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param creationDate  The creationDate of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace creationDate(@Nonnull final String creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate  The creationDate of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getCreationDate() {
    return creationDate;
  }

  /**
  * Set the creationDate of this {@link ContractWorkspace} instance.
  *
  * @param creationDate  The creationDate of this {@link ContractWorkspace}
  */
  public void setCreationDate( @Nonnull final String creationDate) {
    this.creationDate = creationDate;
  }

   /**
   * Set the contractAmount of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param contractAmount  The contractAmount of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace contractAmount(@Nonnull final Money contractAmount) {
    this.contractAmount = contractAmount;
    return this;
  }

   /**
   * Get contractAmount
   * @return contractAmount  The contractAmount of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public Money getContractAmount() {
    return contractAmount;
  }

  /**
  * Set the contractAmount of this {@link ContractWorkspace} instance.
  *
  * @param contractAmount  The contractAmount of this {@link ContractWorkspace}
  */
  public void setContractAmount( @Nonnull final Money contractAmount) {
    this.contractAmount = contractAmount;
  }

   /**
   * Set the proposedContractAmount of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param proposedContractAmount  The proposedContractAmount of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace proposedContractAmount(@Nonnull final Money proposedContractAmount) {
    this.proposedContractAmount = proposedContractAmount;
    return this;
  }

   /**
   * Get proposedContractAmount
   * @return proposedContractAmount  The proposedContractAmount of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public Money getProposedContractAmount() {
    return proposedContractAmount;
  }

  /**
  * Set the proposedContractAmount of this {@link ContractWorkspace} instance.
  *
  * @param proposedContractAmount  The proposedContractAmount of this {@link ContractWorkspace}
  */
  public void setProposedContractAmount( @Nonnull final Money proposedContractAmount) {
    this.proposedContractAmount = proposedContractAmount;
  }

   /**
   * Set the version of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param version  The version of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace version(@Nonnull final Long version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version  The version of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public Long getVersion() {
    return version;
  }

  /**
  * Set the version of this {@link ContractWorkspace} instance.
  *
  * @param version  The version of this {@link ContractWorkspace}
  */
  public void setVersion( @Nonnull final Long version) {
    this.version = version;
  }

   /**
   * Set the maximumNumberOfRenewals of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param maximumNumberOfRenewals  The maximumNumberOfRenewals of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace maximumNumberOfRenewals(@Nonnull final Long maximumNumberOfRenewals) {
    this.maximumNumberOfRenewals = maximumNumberOfRenewals;
    return this;
  }

   /**
   * Get maximumNumberOfRenewals
   * @return maximumNumberOfRenewals  The maximumNumberOfRenewals of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public Long getMaximumNumberOfRenewals() {
    return maximumNumberOfRenewals;
  }

  /**
  * Set the maximumNumberOfRenewals of this {@link ContractWorkspace} instance.
  *
  * @param maximumNumberOfRenewals  The maximumNumberOfRenewals of this {@link ContractWorkspace}
  */
  public void setMaximumNumberOfRenewals( @Nonnull final Long maximumNumberOfRenewals) {
    this.maximumNumberOfRenewals = maximumNumberOfRenewals;
  }

   /**
   * Set the autoRenewalInterval of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param autoRenewalInterval  The autoRenewalInterval of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace autoRenewalInterval(@Nonnull final Long autoRenewalInterval) {
    this.autoRenewalInterval = autoRenewalInterval;
    return this;
  }

   /**
   * Get autoRenewalInterval
   * @return autoRenewalInterval  The autoRenewalInterval of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public Long getAutoRenewalInterval() {
    return autoRenewalInterval;
  }

  /**
  * Set the autoRenewalInterval of this {@link ContractWorkspace} instance.
  *
  * @param autoRenewalInterval  The autoRenewalInterval of this {@link ContractWorkspace}
  */
  public void setAutoRenewalInterval( @Nonnull final Long autoRenewalInterval) {
    this.autoRenewalInterval = autoRenewalInterval;
  }

   /**
   * Set the templateId of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param templateId  The templateId of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace templateId(@Nonnull final String templateId) {
    this.templateId = templateId;
    return this;
  }

   /**
   * Get templateId
   * @return templateId  The templateId of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getTemplateId() {
    return templateId;
  }

  /**
  * Set the templateId of this {@link ContractWorkspace} instance.
  *
  * @param templateId  The templateId of this {@link ContractWorkspace}
  */
  public void setTemplateId( @Nonnull final String templateId) {
    this.templateId = templateId;
  }

   /**
   * Set the businessSystemId of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param businessSystemId  The businessSystemId of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace businessSystemId(@Nonnull final String businessSystemId) {
    this.businessSystemId = businessSystemId;
    return this;
  }

   /**
   * Get businessSystemId
   * @return businessSystemId  The businessSystemId of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getBusinessSystemId() {
    return businessSystemId;
  }

  /**
  * Set the businessSystemId of this {@link ContractWorkspace} instance.
  *
  * @param businessSystemId  The businessSystemId of this {@link ContractWorkspace}
  */
  public void setBusinessSystemId( @Nonnull final String businessSystemId) {
    this.businessSystemId = businessSystemId;
  }

   /**
   * Set the amendmentType of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param amendmentType  The amendmentType of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace amendmentType(@Nonnull final String amendmentType) {
    this.amendmentType = amendmentType;
    return this;
  }

   /**
   * Get amendmentType
   * @return amendmentType  The amendmentType of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getAmendmentType() {
    return amendmentType;
  }

  /**
  * Set the amendmentType of this {@link ContractWorkspace} instance.
  *
  * @param amendmentType  The amendmentType of this {@link ContractWorkspace}
  */
  public void setAmendmentType( @Nonnull final String amendmentType) {
    this.amendmentType = amendmentType;
  }

   /**
   * Set the amendmentReason of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param amendmentReason  The amendmentReason of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace amendmentReason(@Nonnull final String amendmentReason) {
    this.amendmentReason = amendmentReason;
    return this;
  }

   /**
   * Get amendmentReason
   * @return amendmentReason  The amendmentReason of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getAmendmentReason() {
    return amendmentReason;
  }

  /**
  * Set the amendmentReason of this {@link ContractWorkspace} instance.
  *
  * @param amendmentReason  The amendmentReason of this {@link ContractWorkspace}
  */
  public void setAmendmentReason( @Nonnull final String amendmentReason) {
    this.amendmentReason = amendmentReason;
  }

   /**
   * Set the origin of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param origin  The origin of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace origin(@Nonnull final Integer origin) {
    this.origin = origin;
    return this;
  }

   /**
   * Get origin
   * @return origin  The origin of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public Integer getOrigin() {
    return origin;
  }

  /**
  * Set the origin of this {@link ContractWorkspace} instance.
  *
  * @param origin  The origin of this {@link ContractWorkspace}
  */
  public void setOrigin( @Nonnull final Integer origin) {
    this.origin = origin;
  }

   /**
   * Set the contractCreationSupplierClassification of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param contractCreationSupplierClassification  The contractCreationSupplierClassification of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace contractCreationSupplierClassification(@Nonnull final List<SupplierClassificationBean> contractCreationSupplierClassification) {
    this.contractCreationSupplierClassification = contractCreationSupplierClassification;
    return this;
  }
  /**
  * Add one ContractCreationSupplierClassification instance to this {@link ContractWorkspace}.
  * @param contractCreationSupplierClassificationItem The ContractCreationSupplierClassification that should be added
  * @return The same instance of type {@link ContractWorkspace}
  */
  @Nonnull public ContractWorkspace addContractCreationSupplierClassificationItem( @Nonnull final SupplierClassificationBean contractCreationSupplierClassificationItem) {
    if (this.contractCreationSupplierClassification == null) {
      this.contractCreationSupplierClassification = new ArrayList<>();
    }
    this.contractCreationSupplierClassification.add(contractCreationSupplierClassificationItem);
    return this;
  }

   /**
   * Get contractCreationSupplierClassification
   * @return contractCreationSupplierClassification  The contractCreationSupplierClassification of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public List<SupplierClassificationBean> getContractCreationSupplierClassification() {
    return contractCreationSupplierClassification;
  }

  /**
  * Set the contractCreationSupplierClassification of this {@link ContractWorkspace} instance.
  *
  * @param contractCreationSupplierClassification  The contractCreationSupplierClassification of this {@link ContractWorkspace}
  */
  public void setContractCreationSupplierClassification( @Nonnull final List<SupplierClassificationBean> contractCreationSupplierClassification) {
    this.contractCreationSupplierClassification = contractCreationSupplierClassification;
  }

   /**
   * Set the contractPublishingSupplierClassification of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param contractPublishingSupplierClassification  The contractPublishingSupplierClassification of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace contractPublishingSupplierClassification(@Nonnull final List<SupplierClassificationBean> contractPublishingSupplierClassification) {
    this.contractPublishingSupplierClassification = contractPublishingSupplierClassification;
    return this;
  }
  /**
  * Add one ContractPublishingSupplierClassification instance to this {@link ContractWorkspace}.
  * @param contractPublishingSupplierClassificationItem The ContractPublishingSupplierClassification that should be added
  * @return The same instance of type {@link ContractWorkspace}
  */
  @Nonnull public ContractWorkspace addContractPublishingSupplierClassificationItem( @Nonnull final SupplierClassificationBean contractPublishingSupplierClassificationItem) {
    if (this.contractPublishingSupplierClassification == null) {
      this.contractPublishingSupplierClassification = new ArrayList<>();
    }
    this.contractPublishingSupplierClassification.add(contractPublishingSupplierClassificationItem);
    return this;
  }

   /**
   * Get contractPublishingSupplierClassification
   * @return contractPublishingSupplierClassification  The contractPublishingSupplierClassification of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public List<SupplierClassificationBean> getContractPublishingSupplierClassification() {
    return contractPublishingSupplierClassification;
  }

  /**
  * Set the contractPublishingSupplierClassification of this {@link ContractWorkspace} instance.
  *
  * @param contractPublishingSupplierClassification  The contractPublishingSupplierClassification of this {@link ContractWorkspace}
  */
  public void setContractPublishingSupplierClassification( @Nonnull final List<SupplierClassificationBean> contractPublishingSupplierClassification) {
    this.contractPublishingSupplierClassification = contractPublishingSupplierClassification;
  }

   /**
   * Set the contractIntegrationSupplierClassification of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param contractIntegrationSupplierClassification  The contractIntegrationSupplierClassification of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace contractIntegrationSupplierClassification(@Nonnull final List<SupplierClassificationBean> contractIntegrationSupplierClassification) {
    this.contractIntegrationSupplierClassification = contractIntegrationSupplierClassification;
    return this;
  }
  /**
  * Add one ContractIntegrationSupplierClassification instance to this {@link ContractWorkspace}.
  * @param contractIntegrationSupplierClassificationItem The ContractIntegrationSupplierClassification that should be added
  * @return The same instance of type {@link ContractWorkspace}
  */
  @Nonnull public ContractWorkspace addContractIntegrationSupplierClassificationItem( @Nonnull final SupplierClassificationBean contractIntegrationSupplierClassificationItem) {
    if (this.contractIntegrationSupplierClassification == null) {
      this.contractIntegrationSupplierClassification = new ArrayList<>();
    }
    this.contractIntegrationSupplierClassification.add(contractIntegrationSupplierClassificationItem);
    return this;
  }

   /**
   * Get contractIntegrationSupplierClassification
   * @return contractIntegrationSupplierClassification  The contractIntegrationSupplierClassification of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public List<SupplierClassificationBean> getContractIntegrationSupplierClassification() {
    return contractIntegrationSupplierClassification;
  }

  /**
  * Set the contractIntegrationSupplierClassification of this {@link ContractWorkspace} instance.
  *
  * @param contractIntegrationSupplierClassification  The contractIntegrationSupplierClassification of this {@link ContractWorkspace}
  */
  public void setContractIntegrationSupplierClassification( @Nonnull final List<SupplierClassificationBean> contractIntegrationSupplierClassification) {
    this.contractIntegrationSupplierClassification = contractIntegrationSupplierClassification;
  }

   /**
   * Set the customFields of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param customFields  The customFields of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace customFields(@Nonnull final List<CustomField> customFields) {
    this.customFields = customFields;
    return this;
  }
  /**
  * Add one CustomFields instance to this {@link ContractWorkspace}.
  * @param customFieldsItem The CustomFields that should be added
  * @return The same instance of type {@link ContractWorkspace}
  */
  @Nonnull public ContractWorkspace addCustomFieldsItem( @Nonnull final CustomField customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new ArrayList<>();
    }
    this.customFields.add(customFieldsItem);
    return this;
  }

   /**
   * Get customFields
   * @return customFields  The customFields of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public List<CustomField> getCustomFields() {
    return customFields;
  }

  /**
  * Set the customFields of this {@link ContractWorkspace} instance.
  *
  * @param customFields  The customFields of this {@link ContractWorkspace}
  */
  public void setCustomFields( @Nonnull final List<CustomField> customFields) {
    this.customFields = customFields;
  }

   /**
   * Set the relatedId of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param relatedId  The relatedId of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace relatedId(@Nonnull final String relatedId) {
    this.relatedId = relatedId;
    return this;
  }

   /**
   * Get relatedId
   * @return relatedId  The relatedId of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getRelatedId() {
    return relatedId;
  }

  /**
  * Set the relatedId of this {@link ContractWorkspace} instance.
  *
  * @param relatedId  The relatedId of this {@link ContractWorkspace}
  */
  public void setRelatedId( @Nonnull final String relatedId) {
    this.relatedId = relatedId;
  }

   /**
   * Set the accessControl of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param accessControl  The accessControl of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace accessControl(@Nonnull final List<String> accessControl) {
    this.accessControl = accessControl;
    return this;
  }
  /**
  * Add one AccessControl instance to this {@link ContractWorkspace}.
  * @param accessControlItem The AccessControl that should be added
  * @return The same instance of type {@link ContractWorkspace}
  */
  @Nonnull public ContractWorkspace addAccessControlItem( @Nonnull final String accessControlItem) {
    if (this.accessControl == null) {
      this.accessControl = new ArrayList<>();
    }
    this.accessControl.add(accessControlItem);
    return this;
  }

   /**
   * Get accessControl
   * @return accessControl  The accessControl of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public List<String> getAccessControl() {
    return accessControl;
  }

  /**
  * Set the accessControl of this {@link ContractWorkspace} instance.
  *
  * @param accessControl  The accessControl of this {@link ContractWorkspace}
  */
  public void setAccessControl( @Nonnull final List<String> accessControl) {
    this.accessControl = accessControl;
  }

   /**
   * Set the lastModified of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param lastModified  The lastModified of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace lastModified(@Nonnull final String lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Get lastModified
   * @return lastModified  The lastModified of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public String getLastModified() {
    return lastModified;
  }

  /**
  * Set the lastModified of this {@link ContractWorkspace} instance.
  *
  * @param lastModified  The lastModified of this {@link ContractWorkspace}
  */
  public void setLastModified( @Nonnull final String lastModified) {
    this.lastModified = lastModified;
  }

   /**
   * Set the active of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param active  The active of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace active(@Nonnull final Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active  The active of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public Boolean isActive() {
    return active;
  }

  /**
  * Set the active of this {@link ContractWorkspace} instance.
  *
  * @param active  The active of this {@link ContractWorkspace}
  */
  public void setActive( @Nonnull final Boolean active) {
    this.active = active;
  }

   /**
   * Set the blockPublish of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param blockPublish  The blockPublish of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace blockPublish(@Nonnull final Boolean blockPublish) {
    this.blockPublish = blockPublish;
    return this;
  }

   /**
   * Get blockPublish
   * @return blockPublish  The blockPublish of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public Boolean isBlockPublish() {
    return blockPublish;
  }

  /**
  * Set the blockPublish of this {@link ContractWorkspace} instance.
  *
  * @param blockPublish  The blockPublish of this {@link ContractWorkspace}
  */
  public void setBlockPublish( @Nonnull final Boolean blockPublish) {
    this.blockPublish = blockPublish;
  }

   /**
   * Set the integratedSystemRefs of this {@link ContractWorkspace} instance and return the same instance.
   *
   * @param integratedSystemRefs  The integratedSystemRefs of this {@link ContractWorkspace}
   * @return The same instance of this {@link ContractWorkspace} class
   */
   @Nonnull public ContractWorkspace integratedSystemRefs(@Nonnull final List<IntegratedSystemRef> integratedSystemRefs) {
    this.integratedSystemRefs = integratedSystemRefs;
    return this;
  }
  /**
  * Add one IntegratedSystemRefs instance to this {@link ContractWorkspace}.
  * @param integratedSystemRefsItem The IntegratedSystemRefs that should be added
  * @return The same instance of type {@link ContractWorkspace}
  */
  @Nonnull public ContractWorkspace addIntegratedSystemRefsItem( @Nonnull final IntegratedSystemRef integratedSystemRefsItem) {
    if (this.integratedSystemRefs == null) {
      this.integratedSystemRefs = new ArrayList<>();
    }
    this.integratedSystemRefs.add(integratedSystemRefsItem);
    return this;
  }

   /**
   * Get integratedSystemRefs
   * @return integratedSystemRefs  The integratedSystemRefs of this {@link ContractWorkspace} instance.
  **/
  @Nonnull public List<IntegratedSystemRef> getIntegratedSystemRefs() {
    return integratedSystemRefs;
  }

  /**
  * Set the integratedSystemRefs of this {@link ContractWorkspace} instance.
  *
  * @param integratedSystemRefs  The integratedSystemRefs of this {@link ContractWorkspace}
  */
  public void setIntegratedSystemRefs( @Nonnull final List<IntegratedSystemRef> integratedSystemRefs) {
    this.integratedSystemRefs = integratedSystemRefs;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link ContractWorkspace}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link ContractWorkspace}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("ContractWorkspace has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ContractWorkspace contractWorkspace = (ContractWorkspace) o;
    return Objects.equals(this.cloudSdkCustomFields, contractWorkspace.cloudSdkCustomFields) &&
        Objects.equals(this.title, contractWorkspace.title) &&
        Objects.equals(this.description, contractWorkspace.description) &&
        Objects.equals(this.commodities, contractWorkspace.commodities) &&
        Objects.equals(this.regions, contractWorkspace.regions) &&
        Objects.equals(this.departments, contractWorkspace.departments) &&
        Objects.equals(this.questions, contractWorkspace.questions) &&
        Objects.equals(this.owner, contractWorkspace.owner) &&
        Objects.equals(this.eventInternalId, contractWorkspace.eventInternalId) &&
        Objects.equals(this.eventTitle, contractWorkspace.eventTitle) &&
        Objects.equals(this.contractId, contractWorkspace.contractId) &&
        Objects.equals(this.internalId, contractWorkspace.internalId) &&
        Objects.equals(this.contractStatus, contractWorkspace.contractStatus) &&
        Objects.equals(this.isTestProject, contractWorkspace.isTestProject) &&
        Objects.equals(this.supplier, contractWorkspace.supplier) &&
        Objects.equals(this.affectedParties, contractWorkspace.affectedParties) &&
        Objects.equals(this.expirationTermType, contractWorkspace.expirationTermType) &&
        Objects.equals(this.hierarchicalType, contractWorkspace.hierarchicalType) &&
        Objects.equals(this.parentAgreement, contractWorkspace.parentAgreement) &&
        Objects.equals(this.effectiveDate, contractWorkspace.effectiveDate) &&
        Objects.equals(this.agreementDate, contractWorkspace.agreementDate) &&
        Objects.equals(this.expirationDate, contractWorkspace.expirationDate) &&
        Objects.equals(this.creationDate, contractWorkspace.creationDate) &&
        Objects.equals(this.contractAmount, contractWorkspace.contractAmount) &&
        Objects.equals(this.proposedContractAmount, contractWorkspace.proposedContractAmount) &&
        Objects.equals(this.version, contractWorkspace.version) &&
        Objects.equals(this.maximumNumberOfRenewals, contractWorkspace.maximumNumberOfRenewals) &&
        Objects.equals(this.autoRenewalInterval, contractWorkspace.autoRenewalInterval) &&
        Objects.equals(this.templateId, contractWorkspace.templateId) &&
        Objects.equals(this.businessSystemId, contractWorkspace.businessSystemId) &&
        Objects.equals(this.amendmentType, contractWorkspace.amendmentType) &&
        Objects.equals(this.amendmentReason, contractWorkspace.amendmentReason) &&
        Objects.equals(this.origin, contractWorkspace.origin) &&
        Objects.equals(this.contractCreationSupplierClassification, contractWorkspace.contractCreationSupplierClassification) &&
        Objects.equals(this.contractPublishingSupplierClassification, contractWorkspace.contractPublishingSupplierClassification) &&
        Objects.equals(this.contractIntegrationSupplierClassification, contractWorkspace.contractIntegrationSupplierClassification) &&
        Objects.equals(this.customFields, contractWorkspace.customFields) &&
        Objects.equals(this.relatedId, contractWorkspace.relatedId) &&
        Objects.equals(this.accessControl, contractWorkspace.accessControl) &&
        Objects.equals(this.lastModified, contractWorkspace.lastModified) &&
        Objects.equals(this.active, contractWorkspace.active) &&
        Objects.equals(this.blockPublish, contractWorkspace.blockPublish) &&
        Objects.equals(this.integratedSystemRefs, contractWorkspace.integratedSystemRefs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, description, commodities, regions, departments, questions, owner, eventInternalId, eventTitle, contractId, internalId, contractStatus, isTestProject, supplier, affectedParties, expirationTermType, hierarchicalType, parentAgreement, effectiveDate, agreementDate, expirationDate, creationDate, contractAmount, proposedContractAmount, version, maximumNumberOfRenewals, autoRenewalInterval, templateId, businessSystemId, amendmentType, amendmentReason, origin, contractCreationSupplierClassification, contractPublishingSupplierClassification, contractIntegrationSupplierClassification, customFields, relatedId, accessControl, lastModified, active, blockPublish, integratedSystemRefs, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ContractWorkspace {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    commodities: ").append(toIndentedString(commodities)).append("\n");
    sb.append("    regions: ").append(toIndentedString(regions)).append("\n");
    sb.append("    departments: ").append(toIndentedString(departments)).append("\n");
    sb.append("    questions: ").append(toIndentedString(questions)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    eventInternalId: ").append(toIndentedString(eventInternalId)).append("\n");
    sb.append("    eventTitle: ").append(toIndentedString(eventTitle)).append("\n");
    sb.append("    contractId: ").append(toIndentedString(contractId)).append("\n");
    sb.append("    internalId: ").append(toIndentedString(internalId)).append("\n");
    sb.append("    contractStatus: ").append(toIndentedString(contractStatus)).append("\n");
    sb.append("    isTestProject: ").append(toIndentedString(isTestProject)).append("\n");
    sb.append("    supplier: ").append(toIndentedString(supplier)).append("\n");
    sb.append("    affectedParties: ").append(toIndentedString(affectedParties)).append("\n");
    sb.append("    expirationTermType: ").append(toIndentedString(expirationTermType)).append("\n");
    sb.append("    hierarchicalType: ").append(toIndentedString(hierarchicalType)).append("\n");
    sb.append("    parentAgreement: ").append(toIndentedString(parentAgreement)).append("\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    agreementDate: ").append(toIndentedString(agreementDate)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    contractAmount: ").append(toIndentedString(contractAmount)).append("\n");
    sb.append("    proposedContractAmount: ").append(toIndentedString(proposedContractAmount)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    maximumNumberOfRenewals: ").append(toIndentedString(maximumNumberOfRenewals)).append("\n");
    sb.append("    autoRenewalInterval: ").append(toIndentedString(autoRenewalInterval)).append("\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    businessSystemId: ").append(toIndentedString(businessSystemId)).append("\n");
    sb.append("    amendmentType: ").append(toIndentedString(amendmentType)).append("\n");
    sb.append("    amendmentReason: ").append(toIndentedString(amendmentReason)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    contractCreationSupplierClassification: ").append(toIndentedString(contractCreationSupplierClassification)).append("\n");
    sb.append("    contractPublishingSupplierClassification: ").append(toIndentedString(contractPublishingSupplierClassification)).append("\n");
    sb.append("    contractIntegrationSupplierClassification: ").append(toIndentedString(contractIntegrationSupplierClassification)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    relatedId: ").append(toIndentedString(relatedId)).append("\n");
    sb.append("    accessControl: ").append(toIndentedString(accessControl)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    blockPublish: ").append(toIndentedString(blockPublish)).append("\n");
    sb.append("    integratedSystemRefs: ").append(toIndentedString(integratedSystemRefs)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

