

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.cw.model.Address;
import com.sap.openapi.cw.model.Commodity;
import com.sap.openapi.cw.model.Currency;
import com.sap.openapi.cw.model.Department;
import com.sap.openapi.cw.model.Money;
import com.sap.openapi.cw.model.Region;
import com.sap.openapi.cw.model.UnitOfMeasure;
import com.sap.openapi.cw.model.User;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * CustomField
 */

// CHECKSTYLE:OFF
public class CustomField 
// CHECKSTYLE:ON
{
  @JsonProperty("fieldId")
  private String fieldId;

  @JsonProperty("fieldName")
  private String fieldName;

  /**
   * Gets or Sets fieldDataType
   */
  public enum FieldDataTypeEnum {
    /**
    * The BOOLEANVALUE option of this CustomField
    */
    BOOLEANVALUE("booleanValue"),
    
    /**
    * The DATEVALUE option of this CustomField
    */
    DATEVALUE("dateValue"),
    
    /**
    * The BIGDECIMALVALUE option of this CustomField
    */
    BIGDECIMALVALUE("bigDecimalValue"),
    
    /**
    * The INTVALUE option of this CustomField
    */
    INTVALUE("intValue"),
    
    /**
    * The MONEYVALUE option of this CustomField
    */
    MONEYVALUE("moneyValue"),
    
    /**
    * The TEXTVALUE option of this CustomField
    */
    TEXTVALUE("textValue"),
    
    /**
    * The MULTILINETEXTVALUE option of this CustomField
    */
    MULTILINETEXTVALUE("multiLineTextValue"),
    
    /**
    * The PERCENTVALUE option of this CustomField
    */
    PERCENTVALUE("percentValue"),
    
    /**
    * The URLVALUE option of this CustomField
    */
    URLVALUE("urlValue"),
    
    /**
    * The USERMULTISELECTVALUE option of this CustomField
    */
    USERMULTISELECTVALUE("userMultiSelectValue"),
    
    /**
    * The UNITOFMEASUREVALUE option of this CustomField
    */
    UNITOFMEASUREVALUE("unitOfMeasureValue"),
    
    /**
    * The REGIONVALUE option of this CustomField
    */
    REGIONVALUE("regionValue"),
    
    /**
    * The ADDRESSVALUE option of this CustomField
    */
    ADDRESSVALUE("addressValue"),
    
    /**
    * The COMMODITYVALUE option of this CustomField
    */
    COMMODITYVALUE("commodityValue"),
    
    /**
    * The CURRENCYVALUE option of this CustomField
    */
    CURRENCYVALUE("currencyValue"),
    
    /**
    * The DEPARTMENTVALUE option of this CustomField
    */
    DEPARTMENTVALUE("departmentValue"),
    
    /**
    * The FLEXMASTERDATATYPE option of this CustomField
    */
    FLEXMASTERDATATYPE("flexMasterDataType"),
    
    /**
    * The MULTIVALUEDFLEXMASTERDATATYPE option of this CustomField
    */
    MULTIVALUEDFLEXMASTERDATATYPE("multiValuedFlexMasterDataType"),
    
    /**
    * The PRODUCTVALUE option of this CustomField
    */
    PRODUCTVALUE("productValue"),
    
    /**
    * The COUNTRYVALUE option of this CustomField
    */
    COUNTRYVALUE("countryValue"),
    
    /**
    * The TEXTMULTISELECTVALUE option of this CustomField
    */
    TEXTMULTISELECTVALUE("textMultiSelectValue"),
    
    /**
    * The USERVALUE option of this CustomField
    */
    USERVALUE("userValue");

    private String value;

    FieldDataTypeEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type CustomField
    */
    @JsonCreator
    @Nonnull public static FieldDataTypeEnum fromValue(@Nonnull final String value) {
      for (FieldDataTypeEnum b : FieldDataTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("fieldDataType")
  private FieldDataTypeEnum fieldDataType;

  @JsonProperty("booleanValue")
  private Boolean booleanValue;

  @JsonProperty("dateValue")
  private String dateValue;

  @JsonProperty("bigDecimalValue")
  private BigDecimal bigDecimalValue;

  @JsonProperty("intValue")
  private BigDecimal intValue;

  @JsonProperty("moneyValue")
  private Money moneyValue;

  @JsonProperty("textValue")
  private List<String> textValue = new ArrayList<>();

  @JsonProperty("percentValue")
  private BigDecimal percentValue;

  @JsonProperty("urlValue")
  private String urlValue;

  @JsonProperty("userMultiSelectValue")
  private List<User> userMultiSelectValue = new ArrayList<>();

  @JsonProperty("uomValue")
  private UnitOfMeasure uomValue;

  @JsonProperty("regionValue")
  private Region regionValue;

  @JsonProperty("productValue")
  private String productValue;

  @JsonProperty("addressValue")
  private Address addressValue;

  @JsonProperty("commodityValue")
  private Commodity commodityValue;

  @JsonProperty("countryValue")
  private String countryValue;

  @JsonProperty("currencyValue")
  private Currency currencyValue;

  @JsonProperty("departmentValue")
  private Department departmentValue;

  @JsonProperty("flexMasterDataTypeValue")
  private List<String> flexMasterDataTypeValue = new ArrayList<>();

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the fieldId of this {@link CustomField} instance and return the same instance.
   *
   * @param fieldId  The fieldId of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField fieldId(@Nonnull final String fieldId) {
    this.fieldId = fieldId;
    return this;
  }

   /**
   * Get fieldId
   * @return fieldId  The fieldId of this {@link CustomField} instance.
  **/
  @Nonnull public String getFieldId() {
    return fieldId;
  }

  /**
  * Set the fieldId of this {@link CustomField} instance.
  *
  * @param fieldId  The fieldId of this {@link CustomField}
  */
  public void setFieldId( @Nonnull final String fieldId) {
    this.fieldId = fieldId;
  }

   /**
   * Set the fieldName of this {@link CustomField} instance and return the same instance.
   *
   * @param fieldName  The fieldName of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField fieldName(@Nonnull final String fieldName) {
    this.fieldName = fieldName;
    return this;
  }

   /**
   * Get fieldName
   * @return fieldName  The fieldName of this {@link CustomField} instance.
  **/
  @Nonnull public String getFieldName() {
    return fieldName;
  }

  /**
  * Set the fieldName of this {@link CustomField} instance.
  *
  * @param fieldName  The fieldName of this {@link CustomField}
  */
  public void setFieldName( @Nonnull final String fieldName) {
    this.fieldName = fieldName;
  }

   /**
   * Set the fieldDataType of this {@link CustomField} instance and return the same instance.
   *
   * @param fieldDataType  The fieldDataType of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField fieldDataType(@Nonnull final FieldDataTypeEnum fieldDataType) {
    this.fieldDataType = fieldDataType;
    return this;
  }

   /**
   * Get fieldDataType
   * @return fieldDataType  The fieldDataType of this {@link CustomField} instance.
  **/
  @Nonnull public FieldDataTypeEnum getFieldDataType() {
    return fieldDataType;
  }

  /**
  * Set the fieldDataType of this {@link CustomField} instance.
  *
  * @param fieldDataType  The fieldDataType of this {@link CustomField}
  */
  public void setFieldDataType( @Nonnull final FieldDataTypeEnum fieldDataType) {
    this.fieldDataType = fieldDataType;
  }

   /**
   * Set the booleanValue of this {@link CustomField} instance and return the same instance.
   *
   * @param booleanValue  The booleanValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField booleanValue(@Nonnull final Boolean booleanValue) {
    this.booleanValue = booleanValue;
    return this;
  }

   /**
   * Get booleanValue
   * @return booleanValue  The booleanValue of this {@link CustomField} instance.
  **/
  @Nonnull public Boolean isBooleanValue() {
    return booleanValue;
  }

  /**
  * Set the booleanValue of this {@link CustomField} instance.
  *
  * @param booleanValue  The booleanValue of this {@link CustomField}
  */
  public void setBooleanValue( @Nonnull final Boolean booleanValue) {
    this.booleanValue = booleanValue;
  }

   /**
   * Set the dateValue of this {@link CustomField} instance and return the same instance.
   *
   * @param dateValue  The dateValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField dateValue(@Nonnull final String dateValue) {
    this.dateValue = dateValue;
    return this;
  }

   /**
   * Get dateValue
   * @return dateValue  The dateValue of this {@link CustomField} instance.
  **/
  @Nonnull public String getDateValue() {
    return dateValue;
  }

  /**
  * Set the dateValue of this {@link CustomField} instance.
  *
  * @param dateValue  The dateValue of this {@link CustomField}
  */
  public void setDateValue( @Nonnull final String dateValue) {
    this.dateValue = dateValue;
  }

   /**
   * Set the bigDecimalValue of this {@link CustomField} instance and return the same instance.
   *
   * @param bigDecimalValue  The bigDecimalValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField bigDecimalValue(@Nonnull final BigDecimal bigDecimalValue) {
    this.bigDecimalValue = bigDecimalValue;
    return this;
  }

   /**
   * Get bigDecimalValue
   * @return bigDecimalValue  The bigDecimalValue of this {@link CustomField} instance.
  **/
  @Nonnull public BigDecimal getBigDecimalValue() {
    return bigDecimalValue;
  }

  /**
  * Set the bigDecimalValue of this {@link CustomField} instance.
  *
  * @param bigDecimalValue  The bigDecimalValue of this {@link CustomField}
  */
  public void setBigDecimalValue( @Nonnull final BigDecimal bigDecimalValue) {
    this.bigDecimalValue = bigDecimalValue;
  }

   /**
   * Set the intValue of this {@link CustomField} instance and return the same instance.
   *
   * @param intValue  The intValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField intValue(@Nonnull final BigDecimal intValue) {
    this.intValue = intValue;
    return this;
  }

   /**
   * Get intValue
   * @return intValue  The intValue of this {@link CustomField} instance.
  **/
  @Nonnull public BigDecimal getIntValue() {
    return intValue;
  }

  /**
  * Set the intValue of this {@link CustomField} instance.
  *
  * @param intValue  The intValue of this {@link CustomField}
  */
  public void setIntValue( @Nonnull final BigDecimal intValue) {
    this.intValue = intValue;
  }

   /**
   * Set the moneyValue of this {@link CustomField} instance and return the same instance.
   *
   * @param moneyValue  The moneyValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField moneyValue(@Nonnull final Money moneyValue) {
    this.moneyValue = moneyValue;
    return this;
  }

   /**
   * Get moneyValue
   * @return moneyValue  The moneyValue of this {@link CustomField} instance.
  **/
  @Nonnull public Money getMoneyValue() {
    return moneyValue;
  }

  /**
  * Set the moneyValue of this {@link CustomField} instance.
  *
  * @param moneyValue  The moneyValue of this {@link CustomField}
  */
  public void setMoneyValue( @Nonnull final Money moneyValue) {
    this.moneyValue = moneyValue;
  }

   /**
   * Set the textValue of this {@link CustomField} instance and return the same instance.
   *
   * @param textValue  The textValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField textValue(@Nonnull final List<String> textValue) {
    this.textValue = textValue;
    return this;
  }
  /**
  * Add one TextValue instance to this {@link CustomField}.
  * @param textValueItem The TextValue that should be added
  * @return The same instance of type {@link CustomField}
  */
  @Nonnull public CustomField addTextValueItem( @Nonnull final String textValueItem) {
    if (this.textValue == null) {
      this.textValue = new ArrayList<>();
    }
    this.textValue.add(textValueItem);
    return this;
  }

   /**
   * Get textValue
   * @return textValue  The textValue of this {@link CustomField} instance.
  **/
  @Nonnull public List<String> getTextValue() {
    return textValue;
  }

  /**
  * Set the textValue of this {@link CustomField} instance.
  *
  * @param textValue  The textValue of this {@link CustomField}
  */
  public void setTextValue( @Nonnull final List<String> textValue) {
    this.textValue = textValue;
  }

   /**
   * Set the percentValue of this {@link CustomField} instance and return the same instance.
   *
   * @param percentValue  The percentValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField percentValue(@Nonnull final BigDecimal percentValue) {
    this.percentValue = percentValue;
    return this;
  }

   /**
   * Get percentValue
   * @return percentValue  The percentValue of this {@link CustomField} instance.
  **/
  @Nonnull public BigDecimal getPercentValue() {
    return percentValue;
  }

  /**
  * Set the percentValue of this {@link CustomField} instance.
  *
  * @param percentValue  The percentValue of this {@link CustomField}
  */
  public void setPercentValue( @Nonnull final BigDecimal percentValue) {
    this.percentValue = percentValue;
  }

   /**
   * Set the urlValue of this {@link CustomField} instance and return the same instance.
   *
   * @param urlValue  The urlValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField urlValue(@Nonnull final String urlValue) {
    this.urlValue = urlValue;
    return this;
  }

   /**
   * Get urlValue
   * @return urlValue  The urlValue of this {@link CustomField} instance.
  **/
  @Nonnull public String getUrlValue() {
    return urlValue;
  }

  /**
  * Set the urlValue of this {@link CustomField} instance.
  *
  * @param urlValue  The urlValue of this {@link CustomField}
  */
  public void setUrlValue( @Nonnull final String urlValue) {
    this.urlValue = urlValue;
  }

   /**
   * Set the userMultiSelectValue of this {@link CustomField} instance and return the same instance.
   *
   * @param userMultiSelectValue  The userMultiSelectValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField userMultiSelectValue(@Nonnull final List<User> userMultiSelectValue) {
    this.userMultiSelectValue = userMultiSelectValue;
    return this;
  }
  /**
  * Add one UserMultiSelectValue instance to this {@link CustomField}.
  * @param userMultiSelectValueItem The UserMultiSelectValue that should be added
  * @return The same instance of type {@link CustomField}
  */
  @Nonnull public CustomField addUserMultiSelectValueItem( @Nonnull final User userMultiSelectValueItem) {
    if (this.userMultiSelectValue == null) {
      this.userMultiSelectValue = new ArrayList<>();
    }
    this.userMultiSelectValue.add(userMultiSelectValueItem);
    return this;
  }

   /**
   * Get userMultiSelectValue
   * @return userMultiSelectValue  The userMultiSelectValue of this {@link CustomField} instance.
  **/
  @Nonnull public List<User> getUserMultiSelectValue() {
    return userMultiSelectValue;
  }

  /**
  * Set the userMultiSelectValue of this {@link CustomField} instance.
  *
  * @param userMultiSelectValue  The userMultiSelectValue of this {@link CustomField}
  */
  public void setUserMultiSelectValue( @Nonnull final List<User> userMultiSelectValue) {
    this.userMultiSelectValue = userMultiSelectValue;
  }

   /**
   * Set the uomValue of this {@link CustomField} instance and return the same instance.
   *
   * @param uomValue  The uomValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField uomValue(@Nonnull final UnitOfMeasure uomValue) {
    this.uomValue = uomValue;
    return this;
  }

   /**
   * Get uomValue
   * @return uomValue  The uomValue of this {@link CustomField} instance.
  **/
  @Nonnull public UnitOfMeasure getUomValue() {
    return uomValue;
  }

  /**
  * Set the uomValue of this {@link CustomField} instance.
  *
  * @param uomValue  The uomValue of this {@link CustomField}
  */
  public void setUomValue( @Nonnull final UnitOfMeasure uomValue) {
    this.uomValue = uomValue;
  }

   /**
   * Set the regionValue of this {@link CustomField} instance and return the same instance.
   *
   * @param regionValue  The regionValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField regionValue(@Nonnull final Region regionValue) {
    this.regionValue = regionValue;
    return this;
  }

   /**
   * Get regionValue
   * @return regionValue  The regionValue of this {@link CustomField} instance.
  **/
  @Nonnull public Region getRegionValue() {
    return regionValue;
  }

  /**
  * Set the regionValue of this {@link CustomField} instance.
  *
  * @param regionValue  The regionValue of this {@link CustomField}
  */
  public void setRegionValue( @Nonnull final Region regionValue) {
    this.regionValue = regionValue;
  }

   /**
   * Set the productValue of this {@link CustomField} instance and return the same instance.
   *
   * @param productValue  The productValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField productValue(@Nonnull final String productValue) {
    this.productValue = productValue;
    return this;
  }

   /**
   * Get productValue
   * @return productValue  The productValue of this {@link CustomField} instance.
  **/
  @Nonnull public String getProductValue() {
    return productValue;
  }

  /**
  * Set the productValue of this {@link CustomField} instance.
  *
  * @param productValue  The productValue of this {@link CustomField}
  */
  public void setProductValue( @Nonnull final String productValue) {
    this.productValue = productValue;
  }

   /**
   * Set the addressValue of this {@link CustomField} instance and return the same instance.
   *
   * @param addressValue  The addressValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField addressValue(@Nonnull final Address addressValue) {
    this.addressValue = addressValue;
    return this;
  }

   /**
   * Get addressValue
   * @return addressValue  The addressValue of this {@link CustomField} instance.
  **/
  @Nonnull public Address getAddressValue() {
    return addressValue;
  }

  /**
  * Set the addressValue of this {@link CustomField} instance.
  *
  * @param addressValue  The addressValue of this {@link CustomField}
  */
  public void setAddressValue( @Nonnull final Address addressValue) {
    this.addressValue = addressValue;
  }

   /**
   * Set the commodityValue of this {@link CustomField} instance and return the same instance.
   *
   * @param commodityValue  The commodityValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField commodityValue(@Nonnull final Commodity commodityValue) {
    this.commodityValue = commodityValue;
    return this;
  }

   /**
   * Get commodityValue
   * @return commodityValue  The commodityValue of this {@link CustomField} instance.
  **/
  @Nonnull public Commodity getCommodityValue() {
    return commodityValue;
  }

  /**
  * Set the commodityValue of this {@link CustomField} instance.
  *
  * @param commodityValue  The commodityValue of this {@link CustomField}
  */
  public void setCommodityValue( @Nonnull final Commodity commodityValue) {
    this.commodityValue = commodityValue;
  }

   /**
   * Set the countryValue of this {@link CustomField} instance and return the same instance.
   *
   * @param countryValue  The countryValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField countryValue(@Nonnull final String countryValue) {
    this.countryValue = countryValue;
    return this;
  }

   /**
   * Get countryValue
   * @return countryValue  The countryValue of this {@link CustomField} instance.
  **/
  @Nonnull public String getCountryValue() {
    return countryValue;
  }

  /**
  * Set the countryValue of this {@link CustomField} instance.
  *
  * @param countryValue  The countryValue of this {@link CustomField}
  */
  public void setCountryValue( @Nonnull final String countryValue) {
    this.countryValue = countryValue;
  }

   /**
   * Set the currencyValue of this {@link CustomField} instance and return the same instance.
   *
   * @param currencyValue  The currencyValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField currencyValue(@Nonnull final Currency currencyValue) {
    this.currencyValue = currencyValue;
    return this;
  }

   /**
   * Get currencyValue
   * @return currencyValue  The currencyValue of this {@link CustomField} instance.
  **/
  @Nonnull public Currency getCurrencyValue() {
    return currencyValue;
  }

  /**
  * Set the currencyValue of this {@link CustomField} instance.
  *
  * @param currencyValue  The currencyValue of this {@link CustomField}
  */
  public void setCurrencyValue( @Nonnull final Currency currencyValue) {
    this.currencyValue = currencyValue;
  }

   /**
   * Set the departmentValue of this {@link CustomField} instance and return the same instance.
   *
   * @param departmentValue  The departmentValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField departmentValue(@Nonnull final Department departmentValue) {
    this.departmentValue = departmentValue;
    return this;
  }

   /**
   * Get departmentValue
   * @return departmentValue  The departmentValue of this {@link CustomField} instance.
  **/
  @Nonnull public Department getDepartmentValue() {
    return departmentValue;
  }

  /**
  * Set the departmentValue of this {@link CustomField} instance.
  *
  * @param departmentValue  The departmentValue of this {@link CustomField}
  */
  public void setDepartmentValue( @Nonnull final Department departmentValue) {
    this.departmentValue = departmentValue;
  }

   /**
   * Set the flexMasterDataTypeValue of this {@link CustomField} instance and return the same instance.
   *
   * @param flexMasterDataTypeValue  The flexMasterDataTypeValue of this {@link CustomField}
   * @return The same instance of this {@link CustomField} class
   */
   @Nonnull public CustomField flexMasterDataTypeValue(@Nonnull final List<String> flexMasterDataTypeValue) {
    this.flexMasterDataTypeValue = flexMasterDataTypeValue;
    return this;
  }
  /**
  * Add one FlexMasterDataTypeValue instance to this {@link CustomField}.
  * @param flexMasterDataTypeValueItem The FlexMasterDataTypeValue that should be added
  * @return The same instance of type {@link CustomField}
  */
  @Nonnull public CustomField addFlexMasterDataTypeValueItem( @Nonnull final String flexMasterDataTypeValueItem) {
    if (this.flexMasterDataTypeValue == null) {
      this.flexMasterDataTypeValue = new ArrayList<>();
    }
    this.flexMasterDataTypeValue.add(flexMasterDataTypeValueItem);
    return this;
  }

   /**
   * Get flexMasterDataTypeValue
   * @return flexMasterDataTypeValue  The flexMasterDataTypeValue of this {@link CustomField} instance.
  **/
  @Nonnull public List<String> getFlexMasterDataTypeValue() {
    return flexMasterDataTypeValue;
  }

  /**
  * Set the flexMasterDataTypeValue of this {@link CustomField} instance.
  *
  * @param flexMasterDataTypeValue  The flexMasterDataTypeValue of this {@link CustomField}
  */
  public void setFlexMasterDataTypeValue( @Nonnull final List<String> flexMasterDataTypeValue) {
    this.flexMasterDataTypeValue = flexMasterDataTypeValue;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link CustomField}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link CustomField}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("CustomField has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final CustomField customField = (CustomField) o;
    return Objects.equals(this.cloudSdkCustomFields, customField.cloudSdkCustomFields) &&
        Objects.equals(this.fieldId, customField.fieldId) &&
        Objects.equals(this.fieldName, customField.fieldName) &&
        Objects.equals(this.fieldDataType, customField.fieldDataType) &&
        Objects.equals(this.booleanValue, customField.booleanValue) &&
        Objects.equals(this.dateValue, customField.dateValue) &&
        Objects.equals(this.bigDecimalValue, customField.bigDecimalValue) &&
        Objects.equals(this.intValue, customField.intValue) &&
        Objects.equals(this.moneyValue, customField.moneyValue) &&
        Objects.equals(this.textValue, customField.textValue) &&
        Objects.equals(this.percentValue, customField.percentValue) &&
        Objects.equals(this.urlValue, customField.urlValue) &&
        Objects.equals(this.userMultiSelectValue, customField.userMultiSelectValue) &&
        Objects.equals(this.uomValue, customField.uomValue) &&
        Objects.equals(this.regionValue, customField.regionValue) &&
        Objects.equals(this.productValue, customField.productValue) &&
        Objects.equals(this.addressValue, customField.addressValue) &&
        Objects.equals(this.commodityValue, customField.commodityValue) &&
        Objects.equals(this.countryValue, customField.countryValue) &&
        Objects.equals(this.currencyValue, customField.currencyValue) &&
        Objects.equals(this.departmentValue, customField.departmentValue) &&
        Objects.equals(this.flexMasterDataTypeValue, customField.flexMasterDataTypeValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldId, fieldName, fieldDataType, booleanValue, dateValue, bigDecimalValue, intValue, moneyValue, textValue, percentValue, urlValue, userMultiSelectValue, uomValue, regionValue, productValue, addressValue, commodityValue, countryValue, currencyValue, departmentValue, flexMasterDataTypeValue, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class CustomField {\n");
    sb.append("    fieldId: ").append(toIndentedString(fieldId)).append("\n");
    sb.append("    fieldName: ").append(toIndentedString(fieldName)).append("\n");
    sb.append("    fieldDataType: ").append(toIndentedString(fieldDataType)).append("\n");
    sb.append("    booleanValue: ").append(toIndentedString(booleanValue)).append("\n");
    sb.append("    dateValue: ").append(toIndentedString(dateValue)).append("\n");
    sb.append("    bigDecimalValue: ").append(toIndentedString(bigDecimalValue)).append("\n");
    sb.append("    intValue: ").append(toIndentedString(intValue)).append("\n");
    sb.append("    moneyValue: ").append(toIndentedString(moneyValue)).append("\n");
    sb.append("    textValue: ").append(toIndentedString(textValue)).append("\n");
    sb.append("    percentValue: ").append(toIndentedString(percentValue)).append("\n");
    sb.append("    urlValue: ").append(toIndentedString(urlValue)).append("\n");
    sb.append("    userMultiSelectValue: ").append(toIndentedString(userMultiSelectValue)).append("\n");
    sb.append("    uomValue: ").append(toIndentedString(uomValue)).append("\n");
    sb.append("    regionValue: ").append(toIndentedString(regionValue)).append("\n");
    sb.append("    productValue: ").append(toIndentedString(productValue)).append("\n");
    sb.append("    addressValue: ").append(toIndentedString(addressValue)).append("\n");
    sb.append("    commodityValue: ").append(toIndentedString(commodityValue)).append("\n");
    sb.append("    countryValue: ").append(toIndentedString(countryValue)).append("\n");
    sb.append("    currencyValue: ").append(toIndentedString(currencyValue)).append("\n");
    sb.append("    departmentValue: ").append(toIndentedString(departmentValue)).append("\n");
    sb.append("    flexMasterDataTypeValue: ").append(toIndentedString(flexMasterDataTypeValue)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

