

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * ExternalSystemItemInfo
 */

// CHECKSTYLE:OFF
public class ExternalSystemItemInfo 
// CHECKSTYLE:ON
{
  @JsonProperty("paymentTerms")
  private String paymentTerms;

  @JsonProperty("companyCode")
  private String companyCode;

  @JsonProperty("documentType")
  private String documentType;

  @JsonProperty("purchasingOrganization")
  private String purchasingOrganization;

  @JsonProperty("documentCategory")
  private String documentCategory;

  @JsonProperty("purchasingGroup")
  private String purchasingGroup;

  @JsonProperty("lineNumber")
  private String lineNumber;

  @JsonProperty("relatedId")
  private String relatedId;

  @JsonProperty("currency")
  private String currency;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the paymentTerms of this {@link ExternalSystemItemInfo} instance and return the same instance.
   *
   * @param paymentTerms  The paymentTerms of this {@link ExternalSystemItemInfo}
   * @return The same instance of this {@link ExternalSystemItemInfo} class
   */
   @Nonnull public ExternalSystemItemInfo paymentTerms(@Nonnull final String paymentTerms) {
    this.paymentTerms = paymentTerms;
    return this;
  }

   /**
   * Get paymentTerms
   * @return paymentTerms  The paymentTerms of this {@link ExternalSystemItemInfo} instance.
  **/
  @Nonnull public String getPaymentTerms() {
    return paymentTerms;
  }

  /**
  * Set the paymentTerms of this {@link ExternalSystemItemInfo} instance.
  *
  * @param paymentTerms  The paymentTerms of this {@link ExternalSystemItemInfo}
  */
  public void setPaymentTerms( @Nonnull final String paymentTerms) {
    this.paymentTerms = paymentTerms;
  }

   /**
   * Set the companyCode of this {@link ExternalSystemItemInfo} instance and return the same instance.
   *
   * @param companyCode  The companyCode of this {@link ExternalSystemItemInfo}
   * @return The same instance of this {@link ExternalSystemItemInfo} class
   */
   @Nonnull public ExternalSystemItemInfo companyCode(@Nonnull final String companyCode) {
    this.companyCode = companyCode;
    return this;
  }

   /**
   * Get companyCode
   * @return companyCode  The companyCode of this {@link ExternalSystemItemInfo} instance.
  **/
  @Nonnull public String getCompanyCode() {
    return companyCode;
  }

  /**
  * Set the companyCode of this {@link ExternalSystemItemInfo} instance.
  *
  * @param companyCode  The companyCode of this {@link ExternalSystemItemInfo}
  */
  public void setCompanyCode( @Nonnull final String companyCode) {
    this.companyCode = companyCode;
  }

   /**
   * Set the documentType of this {@link ExternalSystemItemInfo} instance and return the same instance.
   *
   * @param documentType  The documentType of this {@link ExternalSystemItemInfo}
   * @return The same instance of this {@link ExternalSystemItemInfo} class
   */
   @Nonnull public ExternalSystemItemInfo documentType(@Nonnull final String documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType  The documentType of this {@link ExternalSystemItemInfo} instance.
  **/
  @Nonnull public String getDocumentType() {
    return documentType;
  }

  /**
  * Set the documentType of this {@link ExternalSystemItemInfo} instance.
  *
  * @param documentType  The documentType of this {@link ExternalSystemItemInfo}
  */
  public void setDocumentType( @Nonnull final String documentType) {
    this.documentType = documentType;
  }

   /**
   * Set the purchasingOrganization of this {@link ExternalSystemItemInfo} instance and return the same instance.
   *
   * @param purchasingOrganization  The purchasingOrganization of this {@link ExternalSystemItemInfo}
   * @return The same instance of this {@link ExternalSystemItemInfo} class
   */
   @Nonnull public ExternalSystemItemInfo purchasingOrganization(@Nonnull final String purchasingOrganization) {
    this.purchasingOrganization = purchasingOrganization;
    return this;
  }

   /**
   * Get purchasingOrganization
   * @return purchasingOrganization  The purchasingOrganization of this {@link ExternalSystemItemInfo} instance.
  **/
  @Nonnull public String getPurchasingOrganization() {
    return purchasingOrganization;
  }

  /**
  * Set the purchasingOrganization of this {@link ExternalSystemItemInfo} instance.
  *
  * @param purchasingOrganization  The purchasingOrganization of this {@link ExternalSystemItemInfo}
  */
  public void setPurchasingOrganization( @Nonnull final String purchasingOrganization) {
    this.purchasingOrganization = purchasingOrganization;
  }

   /**
   * Set the documentCategory of this {@link ExternalSystemItemInfo} instance and return the same instance.
   *
   * @param documentCategory  The documentCategory of this {@link ExternalSystemItemInfo}
   * @return The same instance of this {@link ExternalSystemItemInfo} class
   */
   @Nonnull public ExternalSystemItemInfo documentCategory(@Nonnull final String documentCategory) {
    this.documentCategory = documentCategory;
    return this;
  }

   /**
   * Get documentCategory
   * @return documentCategory  The documentCategory of this {@link ExternalSystemItemInfo} instance.
  **/
  @Nonnull public String getDocumentCategory() {
    return documentCategory;
  }

  /**
  * Set the documentCategory of this {@link ExternalSystemItemInfo} instance.
  *
  * @param documentCategory  The documentCategory of this {@link ExternalSystemItemInfo}
  */
  public void setDocumentCategory( @Nonnull final String documentCategory) {
    this.documentCategory = documentCategory;
  }

   /**
   * Set the purchasingGroup of this {@link ExternalSystemItemInfo} instance and return the same instance.
   *
   * @param purchasingGroup  The purchasingGroup of this {@link ExternalSystemItemInfo}
   * @return The same instance of this {@link ExternalSystemItemInfo} class
   */
   @Nonnull public ExternalSystemItemInfo purchasingGroup(@Nonnull final String purchasingGroup) {
    this.purchasingGroup = purchasingGroup;
    return this;
  }

   /**
   * Get purchasingGroup
   * @return purchasingGroup  The purchasingGroup of this {@link ExternalSystemItemInfo} instance.
  **/
  @Nonnull public String getPurchasingGroup() {
    return purchasingGroup;
  }

  /**
  * Set the purchasingGroup of this {@link ExternalSystemItemInfo} instance.
  *
  * @param purchasingGroup  The purchasingGroup of this {@link ExternalSystemItemInfo}
  */
  public void setPurchasingGroup( @Nonnull final String purchasingGroup) {
    this.purchasingGroup = purchasingGroup;
  }

   /**
   * Set the lineNumber of this {@link ExternalSystemItemInfo} instance and return the same instance.
   *
   * @param lineNumber  The lineNumber of this {@link ExternalSystemItemInfo}
   * @return The same instance of this {@link ExternalSystemItemInfo} class
   */
   @Nonnull public ExternalSystemItemInfo lineNumber(@Nonnull final String lineNumber) {
    this.lineNumber = lineNumber;
    return this;
  }

   /**
   * Get lineNumber
   * @return lineNumber  The lineNumber of this {@link ExternalSystemItemInfo} instance.
  **/
  @Nonnull public String getLineNumber() {
    return lineNumber;
  }

  /**
  * Set the lineNumber of this {@link ExternalSystemItemInfo} instance.
  *
  * @param lineNumber  The lineNumber of this {@link ExternalSystemItemInfo}
  */
  public void setLineNumber( @Nonnull final String lineNumber) {
    this.lineNumber = lineNumber;
  }

   /**
   * Set the relatedId of this {@link ExternalSystemItemInfo} instance and return the same instance.
   *
   * @param relatedId  The relatedId of this {@link ExternalSystemItemInfo}
   * @return The same instance of this {@link ExternalSystemItemInfo} class
   */
   @Nonnull public ExternalSystemItemInfo relatedId(@Nonnull final String relatedId) {
    this.relatedId = relatedId;
    return this;
  }

   /**
   * Get relatedId
   * @return relatedId  The relatedId of this {@link ExternalSystemItemInfo} instance.
  **/
  @Nonnull public String getRelatedId() {
    return relatedId;
  }

  /**
  * Set the relatedId of this {@link ExternalSystemItemInfo} instance.
  *
  * @param relatedId  The relatedId of this {@link ExternalSystemItemInfo}
  */
  public void setRelatedId( @Nonnull final String relatedId) {
    this.relatedId = relatedId;
  }

   /**
   * Set the currency of this {@link ExternalSystemItemInfo} instance and return the same instance.
   *
   * @param currency  The currency of this {@link ExternalSystemItemInfo}
   * @return The same instance of this {@link ExternalSystemItemInfo} class
   */
   @Nonnull public ExternalSystemItemInfo currency(@Nonnull final String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency  The currency of this {@link ExternalSystemItemInfo} instance.
  **/
  @Nonnull public String getCurrency() {
    return currency;
  }

  /**
  * Set the currency of this {@link ExternalSystemItemInfo} instance.
  *
  * @param currency  The currency of this {@link ExternalSystemItemInfo}
  */
  public void setCurrency( @Nonnull final String currency) {
    this.currency = currency;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link ExternalSystemItemInfo}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link ExternalSystemItemInfo}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("ExternalSystemItemInfo has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ExternalSystemItemInfo externalSystemItemInfo = (ExternalSystemItemInfo) o;
    return Objects.equals(this.cloudSdkCustomFields, externalSystemItemInfo.cloudSdkCustomFields) &&
        Objects.equals(this.paymentTerms, externalSystemItemInfo.paymentTerms) &&
        Objects.equals(this.companyCode, externalSystemItemInfo.companyCode) &&
        Objects.equals(this.documentType, externalSystemItemInfo.documentType) &&
        Objects.equals(this.purchasingOrganization, externalSystemItemInfo.purchasingOrganization) &&
        Objects.equals(this.documentCategory, externalSystemItemInfo.documentCategory) &&
        Objects.equals(this.purchasingGroup, externalSystemItemInfo.purchasingGroup) &&
        Objects.equals(this.lineNumber, externalSystemItemInfo.lineNumber) &&
        Objects.equals(this.relatedId, externalSystemItemInfo.relatedId) &&
        Objects.equals(this.currency, externalSystemItemInfo.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentTerms, companyCode, documentType, purchasingOrganization, documentCategory, purchasingGroup, lineNumber, relatedId, currency, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ExternalSystemItemInfo {\n");
    sb.append("    paymentTerms: ").append(toIndentedString(paymentTerms)).append("\n");
    sb.append("    companyCode: ").append(toIndentedString(companyCode)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    purchasingOrganization: ").append(toIndentedString(purchasingOrganization)).append("\n");
    sb.append("    documentCategory: ").append(toIndentedString(documentCategory)).append("\n");
    sb.append("    purchasingGroup: ").append(toIndentedString(purchasingGroup)).append("\n");
    sb.append("    lineNumber: ").append(toIndentedString(lineNumber)).append("\n");
    sb.append("    relatedId: ").append(toIndentedString(relatedId)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

