

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.cw.model.Address;
import com.sap.openapi.cw.model.OrganizationID;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Organization
 */

// CHECKSTYLE:OFF
public class Organization 
// CHECKSTYLE:ON
{
  @JsonProperty("name")
  private String name;

  @JsonProperty("systemID")
  private String systemID;

  @JsonProperty("smVendorID")
  private String smVendorID;

  @JsonProperty("organizationIDs")
  private List<OrganizationID> organizationIDs = new ArrayList<>();

  @JsonProperty("address")
  private Address address;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the name of this {@link Organization} instance and return the same instance.
   *
   * @param name  The name of this {@link Organization}
   * @return The same instance of this {@link Organization} class
   */
   @Nonnull public Organization name(@Nonnull final String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name  The name of this {@link Organization} instance.
  **/
  @Nonnull public String getName() {
    return name;
  }

  /**
  * Set the name of this {@link Organization} instance.
  *
  * @param name  The name of this {@link Organization}
  */
  public void setName( @Nonnull final String name) {
    this.name = name;
  }

   /**
   * Set the systemID of this {@link Organization} instance and return the same instance.
   *
   * @param systemID  The systemID of this {@link Organization}
   * @return The same instance of this {@link Organization} class
   */
   @Nonnull public Organization systemID(@Nonnull final String systemID) {
    this.systemID = systemID;
    return this;
  }

   /**
   * Get systemID
   * @return systemID  The systemID of this {@link Organization} instance.
  **/
  @Nonnull public String getSystemID() {
    return systemID;
  }

  /**
  * Set the systemID of this {@link Organization} instance.
  *
  * @param systemID  The systemID of this {@link Organization}
  */
  public void setSystemID( @Nonnull final String systemID) {
    this.systemID = systemID;
  }

   /**
   * Set the smVendorID of this {@link Organization} instance and return the same instance.
   *
   * @param smVendorID  The smVendorID of this {@link Organization}
   * @return The same instance of this {@link Organization} class
   */
   @Nonnull public Organization smVendorID(@Nonnull final String smVendorID) {
    this.smVendorID = smVendorID;
    return this;
  }

   /**
   * Get smVendorID
   * @return smVendorID  The smVendorID of this {@link Organization} instance.
  **/
  @Nonnull public String getSmVendorID() {
    return smVendorID;
  }

  /**
  * Set the smVendorID of this {@link Organization} instance.
  *
  * @param smVendorID  The smVendorID of this {@link Organization}
  */
  public void setSmVendorID( @Nonnull final String smVendorID) {
    this.smVendorID = smVendorID;
  }

   /**
   * Set the organizationIDs of this {@link Organization} instance and return the same instance.
   *
   * @param organizationIDs  The organizationIDs of this {@link Organization}
   * @return The same instance of this {@link Organization} class
   */
   @Nonnull public Organization organizationIDs(@Nonnull final List<OrganizationID> organizationIDs) {
    this.organizationIDs = organizationIDs;
    return this;
  }
  /**
  * Add one OrganizationIDs instance to this {@link Organization}.
  * @param organizationIDsItem The OrganizationIDs that should be added
  * @return The same instance of type {@link Organization}
  */
  @Nonnull public Organization addOrganizationIDsItem( @Nonnull final OrganizationID organizationIDsItem) {
    if (this.organizationIDs == null) {
      this.organizationIDs = new ArrayList<>();
    }
    this.organizationIDs.add(organizationIDsItem);
    return this;
  }

   /**
   * Get organizationIDs
   * @return organizationIDs  The organizationIDs of this {@link Organization} instance.
  **/
  @Nonnull public List<OrganizationID> getOrganizationIDs() {
    return organizationIDs;
  }

  /**
  * Set the organizationIDs of this {@link Organization} instance.
  *
  * @param organizationIDs  The organizationIDs of this {@link Organization}
  */
  public void setOrganizationIDs( @Nonnull final List<OrganizationID> organizationIDs) {
    this.organizationIDs = organizationIDs;
  }

   /**
   * Set the address of this {@link Organization} instance and return the same instance.
   *
   * @param address  The address of this {@link Organization}
   * @return The same instance of this {@link Organization} class
   */
   @Nonnull public Organization address(@Nonnull final Address address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address  The address of this {@link Organization} instance.
  **/
  @Nonnull public Address getAddress() {
    return address;
  }

  /**
  * Set the address of this {@link Organization} instance.
  *
  * @param address  The address of this {@link Organization}
  */
  public void setAddress( @Nonnull final Address address) {
    this.address = address;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link Organization}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link Organization}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("Organization has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final Organization organization = (Organization) o;
    return Objects.equals(this.cloudSdkCustomFields, organization.cloudSdkCustomFields) &&
        Objects.equals(this.name, organization.name) &&
        Objects.equals(this.systemID, organization.systemID) &&
        Objects.equals(this.smVendorID, organization.smVendorID) &&
        Objects.equals(this.organizationIDs, organization.organizationIDs) &&
        Objects.equals(this.address, organization.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, systemID, smVendorID, organizationIDs, address, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class Organization {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    systemID: ").append(toIndentedString(systemID)).append("\n");
    sb.append("    smVendorID: ").append(toIndentedString(smVendorID)).append("\n");
    sb.append("    organizationIDs: ").append(toIndentedString(organizationIDs)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

