

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * OrganizationID
 */

// CHECKSTYLE:OFF
public class OrganizationID 
// CHECKSTYLE:ON
{
  @JsonProperty("domain")
  private String domain;

  @JsonProperty("value")
  private String value;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the domain of this {@link OrganizationID} instance and return the same instance.
   *
   * @param domain  The domain of this {@link OrganizationID}
   * @return The same instance of this {@link OrganizationID} class
   */
   @Nonnull public OrganizationID domain(@Nonnull final String domain) {
    this.domain = domain;
    return this;
  }

   /**
   * Get domain
   * @return domain  The domain of this {@link OrganizationID} instance.
  **/
  @Nonnull public String getDomain() {
    return domain;
  }

  /**
  * Set the domain of this {@link OrganizationID} instance.
  *
  * @param domain  The domain of this {@link OrganizationID}
  */
  public void setDomain( @Nonnull final String domain) {
    this.domain = domain;
  }

   /**
   * Set the value of this {@link OrganizationID} instance and return the same instance.
   *
   * @param value  The value of this {@link OrganizationID}
   * @return The same instance of this {@link OrganizationID} class
   */
   @Nonnull public OrganizationID value(@Nonnull final String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value  The value of this {@link OrganizationID} instance.
  **/
  @Nonnull public String getValue() {
    return value;
  }

  /**
  * Set the value of this {@link OrganizationID} instance.
  *
  * @param value  The value of this {@link OrganizationID}
  */
  public void setValue( @Nonnull final String value) {
    this.value = value;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link OrganizationID}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link OrganizationID}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("OrganizationID has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final OrganizationID organizationID = (OrganizationID) o;
    return Objects.equals(this.cloudSdkCustomFields, organizationID.cloudSdkCustomFields) &&
        Objects.equals(this.domain, organizationID.domain) &&
        Objects.equals(this.value, organizationID.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domain, value, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationID {\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

