

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Question
 */

// CHECKSTYLE:OFF
public class Question 
// CHECKSTYLE:ON
{
  @JsonProperty("questionId")
  private String questionId;

  @JsonProperty("questionText")
  private String questionText;

  @JsonProperty("answerText")
  private String answerText;

  @JsonProperty("answerOptions")
  private List<String> answerOptions = new ArrayList<>();

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the questionId of this {@link Question} instance and return the same instance.
   *
   * @param questionId  The questionId of this {@link Question}
   * @return The same instance of this {@link Question} class
   */
   @Nonnull public Question questionId(@Nonnull final String questionId) {
    this.questionId = questionId;
    return this;
  }

   /**
   * Get questionId
   * @return questionId  The questionId of this {@link Question} instance.
  **/
  @Nonnull public String getQuestionId() {
    return questionId;
  }

  /**
  * Set the questionId of this {@link Question} instance.
  *
  * @param questionId  The questionId of this {@link Question}
  */
  public void setQuestionId( @Nonnull final String questionId) {
    this.questionId = questionId;
  }

   /**
   * Set the questionText of this {@link Question} instance and return the same instance.
   *
   * @param questionText  The questionText of this {@link Question}
   * @return The same instance of this {@link Question} class
   */
   @Nonnull public Question questionText(@Nonnull final String questionText) {
    this.questionText = questionText;
    return this;
  }

   /**
   * Get questionText
   * @return questionText  The questionText of this {@link Question} instance.
  **/
  @Nonnull public String getQuestionText() {
    return questionText;
  }

  /**
  * Set the questionText of this {@link Question} instance.
  *
  * @param questionText  The questionText of this {@link Question}
  */
  public void setQuestionText( @Nonnull final String questionText) {
    this.questionText = questionText;
  }

   /**
   * Set the answerText of this {@link Question} instance and return the same instance.
   *
   * @param answerText  The answerText of this {@link Question}
   * @return The same instance of this {@link Question} class
   */
   @Nonnull public Question answerText(@Nonnull final String answerText) {
    this.answerText = answerText;
    return this;
  }

   /**
   * Get answerText
   * @return answerText  The answerText of this {@link Question} instance.
  **/
  @Nonnull public String getAnswerText() {
    return answerText;
  }

  /**
  * Set the answerText of this {@link Question} instance.
  *
  * @param answerText  The answerText of this {@link Question}
  */
  public void setAnswerText( @Nonnull final String answerText) {
    this.answerText = answerText;
  }

   /**
   * Set the answerOptions of this {@link Question} instance and return the same instance.
   *
   * @param answerOptions  The answerOptions of this {@link Question}
   * @return The same instance of this {@link Question} class
   */
   @Nonnull public Question answerOptions(@Nonnull final List<String> answerOptions) {
    this.answerOptions = answerOptions;
    return this;
  }
  /**
  * Add one AnswerOptions instance to this {@link Question}.
  * @param answerOptionsItem The AnswerOptions that should be added
  * @return The same instance of type {@link Question}
  */
  @Nonnull public Question addAnswerOptionsItem( @Nonnull final String answerOptionsItem) {
    if (this.answerOptions == null) {
      this.answerOptions = new ArrayList<>();
    }
    this.answerOptions.add(answerOptionsItem);
    return this;
  }

   /**
   * Get answerOptions
   * @return answerOptions  The answerOptions of this {@link Question} instance.
  **/
  @Nonnull public List<String> getAnswerOptions() {
    return answerOptions;
  }

  /**
  * Set the answerOptions of this {@link Question} instance.
  *
  * @param answerOptions  The answerOptions of this {@link Question}
  */
  public void setAnswerOptions( @Nonnull final List<String> answerOptions) {
    this.answerOptions = answerOptions;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link Question}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link Question}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("Question has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final Question question = (Question) o;
    return Objects.equals(this.cloudSdkCustomFields, question.cloudSdkCustomFields) &&
        Objects.equals(this.questionId, question.questionId) &&
        Objects.equals(this.questionText, question.questionText) &&
        Objects.equals(this.answerText, question.answerText) &&
        Objects.equals(this.answerOptions, question.answerOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(questionId, questionText, answerText, answerOptions, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class Question {\n");
    sb.append("    questionId: ").append(toIndentedString(questionId)).append("\n");
    sb.append("    questionText: ").append(toIndentedString(questionText)).append("\n");
    sb.append("    answerText: ").append(toIndentedString(answerText)).append("\n");
    sb.append("    answerOptions: ").append(toIndentedString(answerOptions)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

