

/*
 * Contract Workspace Modification API
 * This Contract Workspace API allows a client application to : -Create the Contract workspace using Ariba TemplateID -Update the Contract workspace using ContractID -Change the state of the contract workspace, identified by the ContractID, to amend or complete amendment. -Deletes the Contract workspace procurement using ContractID
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.cw.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * SupplierClassificationBean
 */

// CHECKSTYLE:OFF
public class SupplierClassificationBean 
// CHECKSTYLE:ON
{
  @JsonProperty("value")
  private String value;

  @JsonProperty("key")
  private String key;

  @JsonProperty("className")
  private String className;

  @JsonProperty("name")
  private String name;

  @JsonProperty("uniqueName")
  private String uniqueName;

  @JsonProperty("active")
  private Boolean active = false;

  @JsonProperty("disabled")
  private Boolean disabled = false;

  @JsonProperty("projectStatus")
  private String projectStatus;

  @JsonProperty("processTypeUniquename")
  private String processTypeUniquename;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the value of this {@link SupplierClassificationBean} instance and return the same instance.
   *
   * @param value  The value of this {@link SupplierClassificationBean}
   * @return The same instance of this {@link SupplierClassificationBean} class
   */
   @Nonnull public SupplierClassificationBean value(@Nonnull final String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value  The value of this {@link SupplierClassificationBean} instance.
  **/
  @Nonnull public String getValue() {
    return value;
  }

  /**
  * Set the value of this {@link SupplierClassificationBean} instance.
  *
  * @param value  The value of this {@link SupplierClassificationBean}
  */
  public void setValue( @Nonnull final String value) {
    this.value = value;
  }

   /**
   * Set the key of this {@link SupplierClassificationBean} instance and return the same instance.
   *
   * @param key  The key of this {@link SupplierClassificationBean}
   * @return The same instance of this {@link SupplierClassificationBean} class
   */
   @Nonnull public SupplierClassificationBean key(@Nonnull final String key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key  The key of this {@link SupplierClassificationBean} instance.
  **/
  @Nonnull public String getKey() {
    return key;
  }

  /**
  * Set the key of this {@link SupplierClassificationBean} instance.
  *
  * @param key  The key of this {@link SupplierClassificationBean}
  */
  public void setKey( @Nonnull final String key) {
    this.key = key;
  }

   /**
   * Set the className of this {@link SupplierClassificationBean} instance and return the same instance.
   *
   * @param className  The className of this {@link SupplierClassificationBean}
   * @return The same instance of this {@link SupplierClassificationBean} class
   */
   @Nonnull public SupplierClassificationBean className(@Nonnull final String className) {
    this.className = className;
    return this;
  }

   /**
   * Get className
   * @return className  The className of this {@link SupplierClassificationBean} instance.
  **/
  @Nonnull public String getClassName() {
    return className;
  }

  /**
  * Set the className of this {@link SupplierClassificationBean} instance.
  *
  * @param className  The className of this {@link SupplierClassificationBean}
  */
  public void setClassName( @Nonnull final String className) {
    this.className = className;
  }

   /**
   * Set the name of this {@link SupplierClassificationBean} instance and return the same instance.
   *
   * @param name  The name of this {@link SupplierClassificationBean}
   * @return The same instance of this {@link SupplierClassificationBean} class
   */
   @Nonnull public SupplierClassificationBean name(@Nonnull final String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name  The name of this {@link SupplierClassificationBean} instance.
  **/
  @Nonnull public String getName() {
    return name;
  }

  /**
  * Set the name of this {@link SupplierClassificationBean} instance.
  *
  * @param name  The name of this {@link SupplierClassificationBean}
  */
  public void setName( @Nonnull final String name) {
    this.name = name;
  }

   /**
   * Set the uniqueName of this {@link SupplierClassificationBean} instance and return the same instance.
   *
   * @param uniqueName  The uniqueName of this {@link SupplierClassificationBean}
   * @return The same instance of this {@link SupplierClassificationBean} class
   */
   @Nonnull public SupplierClassificationBean uniqueName(@Nonnull final String uniqueName) {
    this.uniqueName = uniqueName;
    return this;
  }

   /**
   * Get uniqueName
   * @return uniqueName  The uniqueName of this {@link SupplierClassificationBean} instance.
  **/
  @Nonnull public String getUniqueName() {
    return uniqueName;
  }

  /**
  * Set the uniqueName of this {@link SupplierClassificationBean} instance.
  *
  * @param uniqueName  The uniqueName of this {@link SupplierClassificationBean}
  */
  public void setUniqueName( @Nonnull final String uniqueName) {
    this.uniqueName = uniqueName;
  }

   /**
   * Set the active of this {@link SupplierClassificationBean} instance and return the same instance.
   *
   * @param active  The active of this {@link SupplierClassificationBean}
   * @return The same instance of this {@link SupplierClassificationBean} class
   */
   @Nonnull public SupplierClassificationBean active(@Nonnull final Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active  The active of this {@link SupplierClassificationBean} instance.
  **/
  @Nonnull public Boolean isActive() {
    return active;
  }

  /**
  * Set the active of this {@link SupplierClassificationBean} instance.
  *
  * @param active  The active of this {@link SupplierClassificationBean}
  */
  public void setActive( @Nonnull final Boolean active) {
    this.active = active;
  }

   /**
   * Set the disabled of this {@link SupplierClassificationBean} instance and return the same instance.
   *
   * @param disabled  The disabled of this {@link SupplierClassificationBean}
   * @return The same instance of this {@link SupplierClassificationBean} class
   */
   @Nonnull public SupplierClassificationBean disabled(@Nonnull final Boolean disabled) {
    this.disabled = disabled;
    return this;
  }

   /**
   * Get disabled
   * @return disabled  The disabled of this {@link SupplierClassificationBean} instance.
  **/
  @Nonnull public Boolean isDisabled() {
    return disabled;
  }

  /**
  * Set the disabled of this {@link SupplierClassificationBean} instance.
  *
  * @param disabled  The disabled of this {@link SupplierClassificationBean}
  */
  public void setDisabled( @Nonnull final Boolean disabled) {
    this.disabled = disabled;
  }

   /**
   * Set the projectStatus of this {@link SupplierClassificationBean} instance and return the same instance.
   *
   * @param projectStatus  The projectStatus of this {@link SupplierClassificationBean}
   * @return The same instance of this {@link SupplierClassificationBean} class
   */
   @Nonnull public SupplierClassificationBean projectStatus(@Nonnull final String projectStatus) {
    this.projectStatus = projectStatus;
    return this;
  }

   /**
   * Get projectStatus
   * @return projectStatus  The projectStatus of this {@link SupplierClassificationBean} instance.
  **/
  @Nonnull public String getProjectStatus() {
    return projectStatus;
  }

  /**
  * Set the projectStatus of this {@link SupplierClassificationBean} instance.
  *
  * @param projectStatus  The projectStatus of this {@link SupplierClassificationBean}
  */
  public void setProjectStatus( @Nonnull final String projectStatus) {
    this.projectStatus = projectStatus;
  }

   /**
   * Set the processTypeUniquename of this {@link SupplierClassificationBean} instance and return the same instance.
   *
   * @param processTypeUniquename  The processTypeUniquename of this {@link SupplierClassificationBean}
   * @return The same instance of this {@link SupplierClassificationBean} class
   */
   @Nonnull public SupplierClassificationBean processTypeUniquename(@Nonnull final String processTypeUniquename) {
    this.processTypeUniquename = processTypeUniquename;
    return this;
  }

   /**
   * Get processTypeUniquename
   * @return processTypeUniquename  The processTypeUniquename of this {@link SupplierClassificationBean} instance.
  **/
  @Nonnull public String getProcessTypeUniquename() {
    return processTypeUniquename;
  }

  /**
  * Set the processTypeUniquename of this {@link SupplierClassificationBean} instance.
  *
  * @param processTypeUniquename  The processTypeUniquename of this {@link SupplierClassificationBean}
  */
  public void setProcessTypeUniquename( @Nonnull final String processTypeUniquename) {
    this.processTypeUniquename = processTypeUniquename;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link SupplierClassificationBean}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link SupplierClassificationBean}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("SupplierClassificationBean has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final SupplierClassificationBean supplierClassificationBean = (SupplierClassificationBean) o;
    return Objects.equals(this.cloudSdkCustomFields, supplierClassificationBean.cloudSdkCustomFields) &&
        Objects.equals(this.value, supplierClassificationBean.value) &&
        Objects.equals(this.key, supplierClassificationBean.key) &&
        Objects.equals(this.className, supplierClassificationBean.className) &&
        Objects.equals(this.name, supplierClassificationBean.name) &&
        Objects.equals(this.uniqueName, supplierClassificationBean.uniqueName) &&
        Objects.equals(this.active, supplierClassificationBean.active) &&
        Objects.equals(this.disabled, supplierClassificationBean.disabled) &&
        Objects.equals(this.projectStatus, supplierClassificationBean.projectStatus) &&
        Objects.equals(this.processTypeUniquename, supplierClassificationBean.processTypeUniquename);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, key, className, name, uniqueName, active, disabled, projectStatus, processTypeUniquename, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class SupplierClassificationBean {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    className: ").append(toIndentedString(className)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    uniqueName: ").append(toIndentedString(uniqueName)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    projectStatus: ").append(toIndentedString(projectStatus)).append("\n");
    sb.append("    processTypeUniquename: ").append(toIndentedString(processTypeUniquename)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

